/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: /mnt/e/workspace/git/go-sfml/CSFML/include/SFML/Audio/Audio.i */

#define SWIGMODULE audio
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


 /* Includes the header in the wrapper code */
#include <SFML/Audio.h>
 
#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_audio_781f6cb27eac316e(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_audio_781f6cb27eac316e(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_sfListener_setGlobalVolume_audio_781f6cb27eac316e(float _swig_go_0) {
  float arg1 ;
  
  arg1 = (float)_swig_go_0; 
  
  sfListener_setGlobalVolume(arg1);
  
}


float _wrap_sfListener_getGlobalVolume_audio_781f6cb27eac316e() {
  float result;
  float _swig_go_result;
  
  
  result = (float)sfListener_getGlobalVolume();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_sfListener_setPosition_audio_781f6cb27eac316e(sfVector3f *_swig_go_0) {
  sfVector3f arg1 ;
  sfVector3f *argp1 ;
  
  
  argp1 = (sfVector3f *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null sfVector3f");
  }
  arg1 = (sfVector3f)*argp1;
  
  
  sfListener_setPosition(arg1);
  
}


sfVector3f *_wrap_sfListener_getPosition_audio_781f6cb27eac316e() {
  sfVector3f result;
  sfVector3f *_swig_go_result;
  
  
  result = sfListener_getPosition();
  {
    sfVector3f * resultptr = (sfVector3f *)malloc(sizeof(sfVector3f));
    memmove(resultptr, &result, sizeof(sfVector3f));
    *(sfVector3f **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_sfListener_setDirection_audio_781f6cb27eac316e(sfVector3f *_swig_go_0) {
  sfVector3f arg1 ;
  sfVector3f *argp1 ;
  
  
  argp1 = (sfVector3f *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null sfVector3f");
  }
  arg1 = (sfVector3f)*argp1;
  
  
  sfListener_setDirection(arg1);
  
}


sfVector3f *_wrap_sfListener_getDirection_audio_781f6cb27eac316e() {
  sfVector3f result;
  sfVector3f *_swig_go_result;
  
  
  result = sfListener_getDirection();
  {
    sfVector3f * resultptr = (sfVector3f *)malloc(sizeof(sfVector3f));
    memmove(resultptr, &result, sizeof(sfVector3f));
    *(sfVector3f **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_sfListener_setUpVector_audio_781f6cb27eac316e(sfVector3f *_swig_go_0) {
  sfVector3f arg1 ;
  sfVector3f *argp1 ;
  
  
  argp1 = (sfVector3f *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null sfVector3f");
  }
  arg1 = (sfVector3f)*argp1;
  
  
  sfListener_setUpVector(arg1);
  
}


sfVector3f *_wrap_sfListener_getUpVector_audio_781f6cb27eac316e() {
  sfVector3f result;
  sfVector3f *_swig_go_result;
  
  
  result = sfListener_getUpVector();
  {
    sfVector3f * resultptr = (sfVector3f *)malloc(sizeof(sfVector3f));
    memmove(resultptr, &result, sizeof(sfVector3f));
    *(sfVector3f **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_sfTimeSpan_offset_set_audio_781f6cb27eac316e(sfTimeSpan *_swig_go_0, sfTime *_swig_go_1) {
  sfTimeSpan *arg1 = (sfTimeSpan *) 0 ;
  sfTime arg2 ;
  sfTime *argp2 ;
  
  arg1 = *(sfTimeSpan **)&_swig_go_0; 
  
  argp2 = (sfTime *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null sfTime");
  }
  arg2 = (sfTime)*argp2;
  
  
  if (arg1) (arg1)->offset = arg2;
  
}


sfTime *_wrap_sfTimeSpan_offset_get_audio_781f6cb27eac316e(sfTimeSpan *_swig_go_0) {
  sfTimeSpan *arg1 = (sfTimeSpan *) 0 ;
  sfTime result;
  sfTime *_swig_go_result;
  
  arg1 = *(sfTimeSpan **)&_swig_go_0; 
  
  result =  ((arg1)->offset);
  {
    sfTime * resultptr = (sfTime *)malloc(sizeof(sfTime));
    memmove(resultptr, &result, sizeof(sfTime));
    *(sfTime **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_sfTimeSpan_length_set_audio_781f6cb27eac316e(sfTimeSpan *_swig_go_0, sfTime *_swig_go_1) {
  sfTimeSpan *arg1 = (sfTimeSpan *) 0 ;
  sfTime arg2 ;
  sfTime *argp2 ;
  
  arg1 = *(sfTimeSpan **)&_swig_go_0; 
  
  argp2 = (sfTime *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null sfTime");
  }
  arg2 = (sfTime)*argp2;
  
  
  if (arg1) (arg1)->length = arg2;
  
}


sfTime *_wrap_sfTimeSpan_length_get_audio_781f6cb27eac316e(sfTimeSpan *_swig_go_0) {
  sfTimeSpan *arg1 = (sfTimeSpan *) 0 ;
  sfTime result;
  sfTime *_swig_go_result;
  
  arg1 = *(sfTimeSpan **)&_swig_go_0; 
  
  result =  ((arg1)->length);
  {
    sfTime * resultptr = (sfTime *)malloc(sizeof(sfTime));
    memmove(resultptr, &result, sizeof(sfTime));
    *(sfTime **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


sfTimeSpan *_wrap_new_sfTimeSpan_audio_781f6cb27eac316e() {
  sfTimeSpan *result = 0 ;
  sfTimeSpan *_swig_go_result;
  
  
  result = (sfTimeSpan *)calloc(1, sizeof(sfTimeSpan));
  *(sfTimeSpan **)&_swig_go_result = (sfTimeSpan *)result; 
  return _swig_go_result;
}


void _wrap_delete_sfTimeSpan_audio_781f6cb27eac316e(sfTimeSpan *_swig_go_0) {
  sfTimeSpan *arg1 = (sfTimeSpan *) 0 ;
  
  arg1 = *(sfTimeSpan **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


struct sfMusic *_wrap_sfMusic_createFromFile_audio_781f6cb27eac316e(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  sfMusic *result = 0 ;
  struct sfMusic *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (sfMusic *)sfMusic_createFromFile((char const *)arg1);
  *(sfMusic **)&_swig_go_result = (sfMusic *)result; 
  free(arg1); 
  return _swig_go_result;
}


struct sfMusic *_wrap_sfMusic_createFromMemory_audio_781f6cb27eac316e(void *_swig_go_0, long long _swig_go_1) {
  void *arg1 = (void *) 0 ;
  size_t arg2 ;
  sfMusic *result = 0 ;
  struct sfMusic *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  result = (sfMusic *)sfMusic_createFromMemory((void const *)arg1,arg2);
  *(sfMusic **)&_swig_go_result = (sfMusic *)result; 
  return _swig_go_result;
}


struct sfMusic *_wrap_sfMusic_createFromStream_audio_781f6cb27eac316e(sfInputStream *_swig_go_0) {
  sfInputStream *arg1 = (sfInputStream *) 0 ;
  sfMusic *result = 0 ;
  struct sfMusic *_swig_go_result;
  
  arg1 = *(sfInputStream **)&_swig_go_0; 
  
  result = (sfMusic *)sfMusic_createFromStream(arg1);
  *(sfMusic **)&_swig_go_result = (sfMusic *)result; 
  return _swig_go_result;
}


void _wrap_sfMusic_destroy_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  sfMusic_destroy(arg1);
  
}


void _wrap_sfMusic_setLoop_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0, intgo _swig_go_1) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  sfBool arg2 ;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  arg2 = (sfBool)_swig_go_1; 
  
  sfMusic_setLoop(arg1,arg2);
  
}


intgo _wrap_sfMusic_getLoop_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  sfBool result;
  intgo _swig_go_result;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  result = (sfBool)sfMusic_getLoop((struct sfMusic const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


sfTime *_wrap_sfMusic_getDuration_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  sfTime result;
  sfTime *_swig_go_result;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  result = sfMusic_getDuration((struct sfMusic const *)arg1);
  {
    sfTime * resultptr = (sfTime *)malloc(sizeof(sfTime));
    memmove(resultptr, &result, sizeof(sfTime));
    *(sfTime **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


sfTimeSpan *_wrap_sfMusic_getLoopPoints_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  sfTimeSpan result;
  sfTimeSpan *_swig_go_result;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  result = sfMusic_getLoopPoints((struct sfMusic const *)arg1);
  {
    sfTimeSpan * resultptr = (sfTimeSpan *)malloc(sizeof(sfTimeSpan));
    memmove(resultptr, &result, sizeof(sfTimeSpan));
    *(sfTimeSpan **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_sfMusic_setLoopPoints_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0, sfTimeSpan *_swig_go_1) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  sfTimeSpan arg2 ;
  sfTimeSpan *argp2 ;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  argp2 = (sfTimeSpan *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null sfTimeSpan");
  }
  arg2 = (sfTimeSpan)*argp2;
  
  
  sfMusic_setLoopPoints(arg1,arg2);
  
}


void _wrap_sfMusic_play_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  sfMusic_play(arg1);
  
}


void _wrap_sfMusic_pause_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  sfMusic_pause(arg1);
  
}


void _wrap_sfMusic_stop_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  sfMusic_stop(arg1);
  
}


intgo _wrap_sfMusic_getChannelCount_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  result = (unsigned int)sfMusic_getChannelCount((struct sfMusic const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_sfMusic_getSampleRate_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  result = (unsigned int)sfMusic_getSampleRate((struct sfMusic const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_sfMusic_getStatus_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  sfSoundStatus result;
  intgo _swig_go_result;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  result = (sfSoundStatus)sfMusic_getStatus((struct sfMusic const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


sfTime *_wrap_sfMusic_getPlayingOffset_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  sfTime result;
  sfTime *_swig_go_result;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  result = sfMusic_getPlayingOffset((struct sfMusic const *)arg1);
  {
    sfTime * resultptr = (sfTime *)malloc(sizeof(sfTime));
    memmove(resultptr, &result, sizeof(sfTime));
    *(sfTime **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_sfMusic_setPitch_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0, float _swig_go_1) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  float arg2 ;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  sfMusic_setPitch(arg1,arg2);
  
}


void _wrap_sfMusic_setVolume_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0, float _swig_go_1) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  float arg2 ;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  sfMusic_setVolume(arg1,arg2);
  
}


void _wrap_sfMusic_setPosition_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0, sfVector3f *_swig_go_1) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  sfVector3f arg2 ;
  sfVector3f *argp2 ;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  argp2 = (sfVector3f *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null sfVector3f");
  }
  arg2 = (sfVector3f)*argp2;
  
  
  sfMusic_setPosition(arg1,arg2);
  
}


void _wrap_sfMusic_setRelativeToListener_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0, intgo _swig_go_1) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  sfBool arg2 ;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  arg2 = (sfBool)_swig_go_1; 
  
  sfMusic_setRelativeToListener(arg1,arg2);
  
}


void _wrap_sfMusic_setMinDistance_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0, float _swig_go_1) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  float arg2 ;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  sfMusic_setMinDistance(arg1,arg2);
  
}


void _wrap_sfMusic_setAttenuation_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0, float _swig_go_1) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  float arg2 ;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  sfMusic_setAttenuation(arg1,arg2);
  
}


void _wrap_sfMusic_setPlayingOffset_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0, sfTime *_swig_go_1) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  sfTime arg2 ;
  sfTime *argp2 ;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  argp2 = (sfTime *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null sfTime");
  }
  arg2 = (sfTime)*argp2;
  
  
  sfMusic_setPlayingOffset(arg1,arg2);
  
}


float _wrap_sfMusic_getPitch_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  result = (float)sfMusic_getPitch((struct sfMusic const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_sfMusic_getVolume_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  result = (float)sfMusic_getVolume((struct sfMusic const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


sfVector3f *_wrap_sfMusic_getPosition_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  sfVector3f result;
  sfVector3f *_swig_go_result;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  result = sfMusic_getPosition((struct sfMusic const *)arg1);
  {
    sfVector3f * resultptr = (sfVector3f *)malloc(sizeof(sfVector3f));
    memmove(resultptr, &result, sizeof(sfVector3f));
    *(sfVector3f **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


intgo _wrap_sfMusic_isRelativeToListener_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  sfBool result;
  intgo _swig_go_result;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  result = (sfBool)sfMusic_isRelativeToListener((struct sfMusic const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_sfMusic_getMinDistance_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  result = (float)sfMusic_getMinDistance((struct sfMusic const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_sfMusic_getAttenuation_audio_781f6cb27eac316e(struct sfMusic *_swig_go_0) {
  sfMusic *arg1 = (sfMusic *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(sfMusic **)&_swig_go_0; 
  
  result = (float)sfMusic_getAttenuation((struct sfMusic const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct sfSound *_wrap_sfSound_create_audio_781f6cb27eac316e() {
  sfSound *result = 0 ;
  struct sfSound *_swig_go_result;
  
  
  result = (sfSound *)sfSound_create();
  *(sfSound **)&_swig_go_result = (sfSound *)result; 
  return _swig_go_result;
}


struct sfSound *_wrap_sfSound_copy_audio_781f6cb27eac316e(struct sfSound *_swig_go_0) {
  sfSound *arg1 = (sfSound *) 0 ;
  sfSound *result = 0 ;
  struct sfSound *_swig_go_result;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  result = (sfSound *)sfSound_copy((struct sfSound const *)arg1);
  *(sfSound **)&_swig_go_result = (sfSound *)result; 
  return _swig_go_result;
}


void _wrap_sfSound_destroy_audio_781f6cb27eac316e(struct sfSound *_swig_go_0) {
  sfSound *arg1 = (sfSound *) 0 ;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  sfSound_destroy(arg1);
  
}


void _wrap_sfSound_play_audio_781f6cb27eac316e(struct sfSound *_swig_go_0) {
  sfSound *arg1 = (sfSound *) 0 ;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  sfSound_play(arg1);
  
}


void _wrap_sfSound_pause_audio_781f6cb27eac316e(struct sfSound *_swig_go_0) {
  sfSound *arg1 = (sfSound *) 0 ;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  sfSound_pause(arg1);
  
}


void _wrap_sfSound_stop_audio_781f6cb27eac316e(struct sfSound *_swig_go_0) {
  sfSound *arg1 = (sfSound *) 0 ;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  sfSound_stop(arg1);
  
}


void _wrap_sfSound_setBuffer_audio_781f6cb27eac316e(struct sfSound *_swig_go_0, struct sfSoundBuffer *_swig_go_1) {
  sfSound *arg1 = (sfSound *) 0 ;
  sfSoundBuffer *arg2 = (sfSoundBuffer *) 0 ;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  arg2 = *(sfSoundBuffer **)&_swig_go_1; 
  
  sfSound_setBuffer(arg1,(struct sfSoundBuffer const *)arg2);
  
}


struct sfSoundBuffer *_wrap_sfSound_getBuffer_audio_781f6cb27eac316e(struct sfSound *_swig_go_0) {
  sfSound *arg1 = (sfSound *) 0 ;
  sfSoundBuffer *result = 0 ;
  struct sfSoundBuffer *_swig_go_result;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  result = (sfSoundBuffer *)sfSound_getBuffer((struct sfSound const *)arg1);
  *(sfSoundBuffer **)&_swig_go_result = (sfSoundBuffer *)result; 
  return _swig_go_result;
}


void _wrap_sfSound_setLoop_audio_781f6cb27eac316e(struct sfSound *_swig_go_0, intgo _swig_go_1) {
  sfSound *arg1 = (sfSound *) 0 ;
  sfBool arg2 ;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  arg2 = (sfBool)_swig_go_1; 
  
  sfSound_setLoop(arg1,arg2);
  
}


intgo _wrap_sfSound_getLoop_audio_781f6cb27eac316e(struct sfSound *_swig_go_0) {
  sfSound *arg1 = (sfSound *) 0 ;
  sfBool result;
  intgo _swig_go_result;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  result = (sfBool)sfSound_getLoop((struct sfSound const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_sfSound_getStatus_audio_781f6cb27eac316e(struct sfSound *_swig_go_0) {
  sfSound *arg1 = (sfSound *) 0 ;
  sfSoundStatus result;
  intgo _swig_go_result;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  result = (sfSoundStatus)sfSound_getStatus((struct sfSound const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_sfSound_setPitch_audio_781f6cb27eac316e(struct sfSound *_swig_go_0, float _swig_go_1) {
  sfSound *arg1 = (sfSound *) 0 ;
  float arg2 ;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  sfSound_setPitch(arg1,arg2);
  
}


void _wrap_sfSound_setVolume_audio_781f6cb27eac316e(struct sfSound *_swig_go_0, float _swig_go_1) {
  sfSound *arg1 = (sfSound *) 0 ;
  float arg2 ;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  sfSound_setVolume(arg1,arg2);
  
}


void _wrap_sfSound_setPosition_audio_781f6cb27eac316e(struct sfSound *_swig_go_0, sfVector3f *_swig_go_1) {
  sfSound *arg1 = (sfSound *) 0 ;
  sfVector3f arg2 ;
  sfVector3f *argp2 ;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  argp2 = (sfVector3f *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null sfVector3f");
  }
  arg2 = (sfVector3f)*argp2;
  
  
  sfSound_setPosition(arg1,arg2);
  
}


void _wrap_sfSound_setRelativeToListener_audio_781f6cb27eac316e(struct sfSound *_swig_go_0, intgo _swig_go_1) {
  sfSound *arg1 = (sfSound *) 0 ;
  sfBool arg2 ;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  arg2 = (sfBool)_swig_go_1; 
  
  sfSound_setRelativeToListener(arg1,arg2);
  
}


void _wrap_sfSound_setMinDistance_audio_781f6cb27eac316e(struct sfSound *_swig_go_0, float _swig_go_1) {
  sfSound *arg1 = (sfSound *) 0 ;
  float arg2 ;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  sfSound_setMinDistance(arg1,arg2);
  
}


void _wrap_sfSound_setAttenuation_audio_781f6cb27eac316e(struct sfSound *_swig_go_0, float _swig_go_1) {
  sfSound *arg1 = (sfSound *) 0 ;
  float arg2 ;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  sfSound_setAttenuation(arg1,arg2);
  
}


void _wrap_sfSound_setPlayingOffset_audio_781f6cb27eac316e(struct sfSound *_swig_go_0, sfTime *_swig_go_1) {
  sfSound *arg1 = (sfSound *) 0 ;
  sfTime arg2 ;
  sfTime *argp2 ;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  argp2 = (sfTime *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null sfTime");
  }
  arg2 = (sfTime)*argp2;
  
  
  sfSound_setPlayingOffset(arg1,arg2);
  
}


float _wrap_sfSound_getPitch_audio_781f6cb27eac316e(struct sfSound *_swig_go_0) {
  sfSound *arg1 = (sfSound *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  result = (float)sfSound_getPitch((struct sfSound const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_sfSound_getVolume_audio_781f6cb27eac316e(struct sfSound *_swig_go_0) {
  sfSound *arg1 = (sfSound *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  result = (float)sfSound_getVolume((struct sfSound const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


sfVector3f *_wrap_sfSound_getPosition_audio_781f6cb27eac316e(struct sfSound *_swig_go_0) {
  sfSound *arg1 = (sfSound *) 0 ;
  sfVector3f result;
  sfVector3f *_swig_go_result;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  result = sfSound_getPosition((struct sfSound const *)arg1);
  {
    sfVector3f * resultptr = (sfVector3f *)malloc(sizeof(sfVector3f));
    memmove(resultptr, &result, sizeof(sfVector3f));
    *(sfVector3f **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


intgo _wrap_sfSound_isRelativeToListener_audio_781f6cb27eac316e(struct sfSound *_swig_go_0) {
  sfSound *arg1 = (sfSound *) 0 ;
  sfBool result;
  intgo _swig_go_result;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  result = (sfBool)sfSound_isRelativeToListener((struct sfSound const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_sfSound_getMinDistance_audio_781f6cb27eac316e(struct sfSound *_swig_go_0) {
  sfSound *arg1 = (sfSound *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  result = (float)sfSound_getMinDistance((struct sfSound const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_sfSound_getAttenuation_audio_781f6cb27eac316e(struct sfSound *_swig_go_0) {
  sfSound *arg1 = (sfSound *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  result = (float)sfSound_getAttenuation((struct sfSound const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


sfTime *_wrap_sfSound_getPlayingOffset_audio_781f6cb27eac316e(struct sfSound *_swig_go_0) {
  sfSound *arg1 = (sfSound *) 0 ;
  sfTime result;
  sfTime *_swig_go_result;
  
  arg1 = *(sfSound **)&_swig_go_0; 
  
  result = sfSound_getPlayingOffset((struct sfSound const *)arg1);
  {
    sfTime * resultptr = (sfTime *)malloc(sizeof(sfTime));
    memmove(resultptr, &result, sizeof(sfTime));
    *(sfTime **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct sfSoundBuffer *_wrap_sfSoundBuffer_createFromFile_audio_781f6cb27eac316e(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  sfSoundBuffer *result = 0 ;
  struct sfSoundBuffer *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (sfSoundBuffer *)sfSoundBuffer_createFromFile((char const *)arg1);
  *(sfSoundBuffer **)&_swig_go_result = (sfSoundBuffer *)result; 
  free(arg1); 
  return _swig_go_result;
}


struct sfSoundBuffer *_wrap_sfSoundBuffer_createFromMemory_audio_781f6cb27eac316e(void *_swig_go_0, long long _swig_go_1) {
  void *arg1 = (void *) 0 ;
  size_t arg2 ;
  sfSoundBuffer *result = 0 ;
  struct sfSoundBuffer *_swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  result = (sfSoundBuffer *)sfSoundBuffer_createFromMemory((void const *)arg1,arg2);
  *(sfSoundBuffer **)&_swig_go_result = (sfSoundBuffer *)result; 
  return _swig_go_result;
}


struct sfSoundBuffer *_wrap_sfSoundBuffer_createFromStream_audio_781f6cb27eac316e(sfInputStream *_swig_go_0) {
  sfInputStream *arg1 = (sfInputStream *) 0 ;
  sfSoundBuffer *result = 0 ;
  struct sfSoundBuffer *_swig_go_result;
  
  arg1 = *(sfInputStream **)&_swig_go_0; 
  
  result = (sfSoundBuffer *)sfSoundBuffer_createFromStream(arg1);
  *(sfSoundBuffer **)&_swig_go_result = (sfSoundBuffer *)result; 
  return _swig_go_result;
}


struct sfSoundBuffer *_wrap_sfSoundBuffer_createFromSamples_audio_781f6cb27eac316e(short *_swig_go_0, long long _swig_go_1, intgo _swig_go_2, intgo _swig_go_3) {
  sfInt16 *arg1 = (sfInt16 *) 0 ;
  sfUint64 arg2 ;
  unsigned int arg3 ;
  unsigned int arg4 ;
  sfSoundBuffer *result = 0 ;
  struct sfSoundBuffer *_swig_go_result;
  
  arg1 = *(sfInt16 **)&_swig_go_0; 
  arg2 = (sfUint64)_swig_go_1; 
  arg3 = (unsigned int)_swig_go_2; 
  arg4 = (unsigned int)_swig_go_3; 
  
  result = (sfSoundBuffer *)sfSoundBuffer_createFromSamples((short const *)arg1,arg2,arg3,arg4);
  *(sfSoundBuffer **)&_swig_go_result = (sfSoundBuffer *)result; 
  return _swig_go_result;
}


struct sfSoundBuffer *_wrap_sfSoundBuffer_copy_audio_781f6cb27eac316e(struct sfSoundBuffer *_swig_go_0) {
  sfSoundBuffer *arg1 = (sfSoundBuffer *) 0 ;
  sfSoundBuffer *result = 0 ;
  struct sfSoundBuffer *_swig_go_result;
  
  arg1 = *(sfSoundBuffer **)&_swig_go_0; 
  
  result = (sfSoundBuffer *)sfSoundBuffer_copy((struct sfSoundBuffer const *)arg1);
  *(sfSoundBuffer **)&_swig_go_result = (sfSoundBuffer *)result; 
  return _swig_go_result;
}


void _wrap_sfSoundBuffer_destroy_audio_781f6cb27eac316e(struct sfSoundBuffer *_swig_go_0) {
  sfSoundBuffer *arg1 = (sfSoundBuffer *) 0 ;
  
  arg1 = *(sfSoundBuffer **)&_swig_go_0; 
  
  sfSoundBuffer_destroy(arg1);
  
}


intgo _wrap_sfSoundBuffer_saveToFile_audio_781f6cb27eac316e(struct sfSoundBuffer *_swig_go_0, _gostring_ _swig_go_1) {
  sfSoundBuffer *arg1 = (sfSoundBuffer *) 0 ;
  char *arg2 = (char *) 0 ;
  sfBool result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundBuffer **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (sfBool)sfSoundBuffer_saveToFile((struct sfSoundBuffer const *)arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


short *_wrap_sfSoundBuffer_getSamples_audio_781f6cb27eac316e(struct sfSoundBuffer *_swig_go_0) {
  sfSoundBuffer *arg1 = (sfSoundBuffer *) 0 ;
  sfInt16 *result = 0 ;
  short *_swig_go_result;
  
  arg1 = *(sfSoundBuffer **)&_swig_go_0; 
  
  result = (sfInt16 *)sfSoundBuffer_getSamples((struct sfSoundBuffer const *)arg1);
  *(sfInt16 **)&_swig_go_result = (sfInt16 *)result; 
  return _swig_go_result;
}


long long _wrap_sfSoundBuffer_getSampleCount_audio_781f6cb27eac316e(struct sfSoundBuffer *_swig_go_0) {
  sfSoundBuffer *arg1 = (sfSoundBuffer *) 0 ;
  sfUint64 result;
  long long _swig_go_result;
  
  arg1 = *(sfSoundBuffer **)&_swig_go_0; 
  
  result = (sfUint64)sfSoundBuffer_getSampleCount((struct sfSoundBuffer const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_sfSoundBuffer_getSampleRate_audio_781f6cb27eac316e(struct sfSoundBuffer *_swig_go_0) {
  sfSoundBuffer *arg1 = (sfSoundBuffer *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundBuffer **)&_swig_go_0; 
  
  result = (unsigned int)sfSoundBuffer_getSampleRate((struct sfSoundBuffer const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_sfSoundBuffer_getChannelCount_audio_781f6cb27eac316e(struct sfSoundBuffer *_swig_go_0) {
  sfSoundBuffer *arg1 = (sfSoundBuffer *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundBuffer **)&_swig_go_0; 
  
  result = (unsigned int)sfSoundBuffer_getChannelCount((struct sfSoundBuffer const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


sfTime *_wrap_sfSoundBuffer_getDuration_audio_781f6cb27eac316e(struct sfSoundBuffer *_swig_go_0) {
  sfSoundBuffer *arg1 = (sfSoundBuffer *) 0 ;
  sfTime result;
  sfTime *_swig_go_result;
  
  arg1 = *(sfSoundBuffer **)&_swig_go_0; 
  
  result = sfSoundBuffer_getDuration((struct sfSoundBuffer const *)arg1);
  {
    sfTime * resultptr = (sfTime *)malloc(sizeof(sfTime));
    memmove(resultptr, &result, sizeof(sfTime));
    *(sfTime **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct sfSoundBufferRecorder *_wrap_sfSoundBufferRecorder_create_audio_781f6cb27eac316e() {
  sfSoundBufferRecorder *result = 0 ;
  struct sfSoundBufferRecorder *_swig_go_result;
  
  
  result = (sfSoundBufferRecorder *)sfSoundBufferRecorder_create();
  *(sfSoundBufferRecorder **)&_swig_go_result = (sfSoundBufferRecorder *)result; 
  return _swig_go_result;
}


void _wrap_sfSoundBufferRecorder_destroy_audio_781f6cb27eac316e(struct sfSoundBufferRecorder *_swig_go_0) {
  sfSoundBufferRecorder *arg1 = (sfSoundBufferRecorder *) 0 ;
  
  arg1 = *(sfSoundBufferRecorder **)&_swig_go_0; 
  
  sfSoundBufferRecorder_destroy(arg1);
  
}


intgo _wrap_sfSoundBufferRecorder_start_audio_781f6cb27eac316e(struct sfSoundBufferRecorder *_swig_go_0, intgo _swig_go_1) {
  sfSoundBufferRecorder *arg1 = (sfSoundBufferRecorder *) 0 ;
  unsigned int arg2 ;
  sfBool result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundBufferRecorder **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  
  result = (sfBool)sfSoundBufferRecorder_start(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_sfSoundBufferRecorder_stop_audio_781f6cb27eac316e(struct sfSoundBufferRecorder *_swig_go_0) {
  sfSoundBufferRecorder *arg1 = (sfSoundBufferRecorder *) 0 ;
  
  arg1 = *(sfSoundBufferRecorder **)&_swig_go_0; 
  
  sfSoundBufferRecorder_stop(arg1);
  
}


intgo _wrap_sfSoundBufferRecorder_getSampleRate_audio_781f6cb27eac316e(struct sfSoundBufferRecorder *_swig_go_0) {
  sfSoundBufferRecorder *arg1 = (sfSoundBufferRecorder *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundBufferRecorder **)&_swig_go_0; 
  
  result = (unsigned int)sfSoundBufferRecorder_getSampleRate((struct sfSoundBufferRecorder const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct sfSoundBuffer *_wrap_sfSoundBufferRecorder_getBuffer_audio_781f6cb27eac316e(struct sfSoundBufferRecorder *_swig_go_0) {
  sfSoundBufferRecorder *arg1 = (sfSoundBufferRecorder *) 0 ;
  sfSoundBuffer *result = 0 ;
  struct sfSoundBuffer *_swig_go_result;
  
  arg1 = *(sfSoundBufferRecorder **)&_swig_go_0; 
  
  result = (sfSoundBuffer *)sfSoundBufferRecorder_getBuffer((struct sfSoundBufferRecorder const *)arg1);
  *(sfSoundBuffer **)&_swig_go_result = (sfSoundBuffer *)result; 
  return _swig_go_result;
}


intgo _wrap_sfSoundBufferRecorder_setDevice_audio_781f6cb27eac316e(struct sfSoundBufferRecorder *_swig_go_0, _gostring_ _swig_go_1) {
  sfSoundBufferRecorder *arg1 = (sfSoundBufferRecorder *) 0 ;
  char *arg2 = (char *) 0 ;
  sfBool result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundBufferRecorder **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (sfBool)sfSoundBufferRecorder_setDevice(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


_gostring_ _wrap_sfSoundBufferRecorder_getDevice_audio_781f6cb27eac316e(struct sfSoundBufferRecorder *_swig_go_0) {
  sfSoundBufferRecorder *arg1 = (sfSoundBufferRecorder *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(sfSoundBufferRecorder **)&_swig_go_0; 
  
  result = (char *)sfSoundBufferRecorder_getDevice(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


struct sfSoundRecorder *_wrap_sfSoundRecorder_create_audio_781f6cb27eac316e(void* _swig_go_0, void* _swig_go_1, void* _swig_go_2, void *_swig_go_3) {
  sfSoundRecorderStartCallback arg1 = (sfSoundRecorderStartCallback) 0 ;
  sfSoundRecorderProcessCallback arg2 = (sfSoundRecorderProcessCallback) 0 ;
  sfSoundRecorderStopCallback arg3 = (sfSoundRecorderStopCallback) 0 ;
  void *arg4 = (void *) 0 ;
  sfSoundRecorder *result = 0 ;
  struct sfSoundRecorder *_swig_go_result;
  
  arg1 = *(sfSoundRecorderStartCallback *)&_swig_go_0; 
  arg2 = *(sfSoundRecorderProcessCallback *)&_swig_go_1; 
  arg3 = *(sfSoundRecorderStopCallback *)&_swig_go_2; 
  arg4 = *(void **)&_swig_go_3; 
  
  result = (sfSoundRecorder *)sfSoundRecorder_create(arg1,arg2,arg3,arg4);
  *(sfSoundRecorder **)&_swig_go_result = (sfSoundRecorder *)result; 
  return _swig_go_result;
}


void _wrap_sfSoundRecorder_destroy_audio_781f6cb27eac316e(struct sfSoundRecorder *_swig_go_0) {
  sfSoundRecorder *arg1 = (sfSoundRecorder *) 0 ;
  
  arg1 = *(sfSoundRecorder **)&_swig_go_0; 
  
  sfSoundRecorder_destroy(arg1);
  
}


intgo _wrap_sfSoundRecorder_start_audio_781f6cb27eac316e(struct sfSoundRecorder *_swig_go_0, intgo _swig_go_1) {
  sfSoundRecorder *arg1 = (sfSoundRecorder *) 0 ;
  unsigned int arg2 ;
  sfBool result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundRecorder **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  
  result = (sfBool)sfSoundRecorder_start(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_sfSoundRecorder_stop_audio_781f6cb27eac316e(struct sfSoundRecorder *_swig_go_0) {
  sfSoundRecorder *arg1 = (sfSoundRecorder *) 0 ;
  
  arg1 = *(sfSoundRecorder **)&_swig_go_0; 
  
  sfSoundRecorder_stop(arg1);
  
}


intgo _wrap_sfSoundRecorder_getSampleRate_audio_781f6cb27eac316e(struct sfSoundRecorder *_swig_go_0) {
  sfSoundRecorder *arg1 = (sfSoundRecorder *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundRecorder **)&_swig_go_0; 
  
  result = (unsigned int)sfSoundRecorder_getSampleRate((struct sfSoundRecorder const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_sfSoundRecorder_isAvailable_audio_781f6cb27eac316e() {
  sfBool result;
  intgo _swig_go_result;
  
  
  result = (sfBool)sfSoundRecorder_isAvailable();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_sfSoundRecorder_setProcessingInterval_audio_781f6cb27eac316e(struct sfSoundRecorder *_swig_go_0, sfTime *_swig_go_1) {
  sfSoundRecorder *arg1 = (sfSoundRecorder *) 0 ;
  sfTime arg2 ;
  sfTime *argp2 ;
  
  arg1 = *(sfSoundRecorder **)&_swig_go_0; 
  
  argp2 = (sfTime *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null sfTime");
  }
  arg2 = (sfTime)*argp2;
  
  
  sfSoundRecorder_setProcessingInterval(arg1,arg2);
  
}


_gostring_* _wrap_sfSoundRecorder_getAvailableDevices_audio_781f6cb27eac316e(long long *_swig_go_0) {
  size_t *arg1 = (size_t *) 0 ;
  char **result = 0 ;
  _gostring_* _swig_go_result;
  
  arg1 = *(size_t **)&_swig_go_0; 
  
  result = (char **)sfSoundRecorder_getAvailableDevices(arg1);
  *(char ***)&_swig_go_result = (char **)result; 
  return _swig_go_result;
}


_gostring_ _wrap_sfSoundRecorder_getDefaultDevice_audio_781f6cb27eac316e() {
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  result = (char *)sfSoundRecorder_getDefaultDevice();
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_sfSoundRecorder_setDevice_audio_781f6cb27eac316e(struct sfSoundRecorder *_swig_go_0, _gostring_ _swig_go_1) {
  sfSoundRecorder *arg1 = (sfSoundRecorder *) 0 ;
  char *arg2 = (char *) 0 ;
  sfBool result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundRecorder **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (sfBool)sfSoundRecorder_setDevice(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


_gostring_ _wrap_sfSoundRecorder_getDevice_audio_781f6cb27eac316e(struct sfSoundRecorder *_swig_go_0) {
  sfSoundRecorder *arg1 = (sfSoundRecorder *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(sfSoundRecorder **)&_swig_go_0; 
  
  result = (char *)sfSoundRecorder_getDevice(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_sfSoundRecorder_setChannelCount_audio_781f6cb27eac316e(struct sfSoundRecorder *_swig_go_0, intgo _swig_go_1) {
  sfSoundRecorder *arg1 = (sfSoundRecorder *) 0 ;
  unsigned int arg2 ;
  
  arg1 = *(sfSoundRecorder **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  
  sfSoundRecorder_setChannelCount(arg1,arg2);
  
}


intgo _wrap_sfSoundRecorder_getChannelCount_audio_781f6cb27eac316e(struct sfSoundRecorder *_swig_go_0) {
  sfSoundRecorder *arg1 = (sfSoundRecorder *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundRecorder **)&_swig_go_0; 
  
  result = (unsigned int)sfSoundRecorder_getChannelCount((struct sfSoundRecorder const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_sfStopped_audio_781f6cb27eac316e() {
  int result;
  intgo _swig_go_result;
  
  
  result = sfStopped;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_sfPaused_audio_781f6cb27eac316e() {
  int result;
  intgo _swig_go_result;
  
  
  result = sfPaused;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_sfPlaying_audio_781f6cb27eac316e() {
  int result;
  intgo _swig_go_result;
  
  
  result = sfPlaying;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_sfSoundStreamChunk_samples_set_audio_781f6cb27eac316e(sfSoundStreamChunk *_swig_go_0, short *_swig_go_1) {
  sfSoundStreamChunk *arg1 = (sfSoundStreamChunk *) 0 ;
  sfInt16 *arg2 = (sfInt16 *) 0 ;
  
  arg1 = *(sfSoundStreamChunk **)&_swig_go_0; 
  arg2 = *(sfInt16 **)&_swig_go_1; 
  
  if (arg1) (arg1)->samples = arg2;
  
}


short *_wrap_sfSoundStreamChunk_samples_get_audio_781f6cb27eac316e(sfSoundStreamChunk *_swig_go_0) {
  sfSoundStreamChunk *arg1 = (sfSoundStreamChunk *) 0 ;
  sfInt16 *result = 0 ;
  short *_swig_go_result;
  
  arg1 = *(sfSoundStreamChunk **)&_swig_go_0; 
  
  result = (sfInt16 *) ((arg1)->samples);
  *(sfInt16 **)&_swig_go_result = (sfInt16 *)result; 
  return _swig_go_result;
}


void _wrap_sfSoundStreamChunk_sampleCount_set_audio_781f6cb27eac316e(sfSoundStreamChunk *_swig_go_0, intgo _swig_go_1) {
  sfSoundStreamChunk *arg1 = (sfSoundStreamChunk *) 0 ;
  unsigned int arg2 ;
  
  arg1 = *(sfSoundStreamChunk **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  
  if (arg1) (arg1)->sampleCount = arg2;
  
}


intgo _wrap_sfSoundStreamChunk_sampleCount_get_audio_781f6cb27eac316e(sfSoundStreamChunk *_swig_go_0) {
  sfSoundStreamChunk *arg1 = (sfSoundStreamChunk *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundStreamChunk **)&_swig_go_0; 
  
  result = (unsigned int) ((arg1)->sampleCount);
  _swig_go_result = result; 
  return _swig_go_result;
}


sfSoundStreamChunk *_wrap_new_sfSoundStreamChunk_audio_781f6cb27eac316e() {
  sfSoundStreamChunk *result = 0 ;
  sfSoundStreamChunk *_swig_go_result;
  
  
  result = (sfSoundStreamChunk *)calloc(1, sizeof(sfSoundStreamChunk));
  *(sfSoundStreamChunk **)&_swig_go_result = (sfSoundStreamChunk *)result; 
  return _swig_go_result;
}


void _wrap_delete_sfSoundStreamChunk_audio_781f6cb27eac316e(sfSoundStreamChunk *_swig_go_0) {
  sfSoundStreamChunk *arg1 = (sfSoundStreamChunk *) 0 ;
  
  arg1 = *(sfSoundStreamChunk **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


struct sfSoundStream *_wrap_sfSoundStream_create_audio_781f6cb27eac316e(void* _swig_go_0, void* _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, void *_swig_go_4) {
  sfSoundStreamGetDataCallback arg1 = (sfSoundStreamGetDataCallback) 0 ;
  sfSoundStreamSeekCallback arg2 = (sfSoundStreamSeekCallback) 0 ;
  unsigned int arg3 ;
  unsigned int arg4 ;
  void *arg5 = (void *) 0 ;
  sfSoundStream *result = 0 ;
  struct sfSoundStream *_swig_go_result;
  
  arg1 = *(sfSoundStreamGetDataCallback *)&_swig_go_0; 
  arg2 = *(sfSoundStreamSeekCallback *)&_swig_go_1; 
  arg3 = (unsigned int)_swig_go_2; 
  arg4 = (unsigned int)_swig_go_3; 
  arg5 = *(void **)&_swig_go_4; 
  
  result = (sfSoundStream *)sfSoundStream_create(arg1,arg2,arg3,arg4,arg5);
  *(sfSoundStream **)&_swig_go_result = (sfSoundStream *)result; 
  return _swig_go_result;
}


void _wrap_sfSoundStream_destroy_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  sfSoundStream_destroy(arg1);
  
}


void _wrap_sfSoundStream_play_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  sfSoundStream_play(arg1);
  
}


void _wrap_sfSoundStream_pause_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  sfSoundStream_pause(arg1);
  
}


void _wrap_sfSoundStream_stop_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  sfSoundStream_stop(arg1);
  
}


intgo _wrap_sfSoundStream_getStatus_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  sfSoundStatus result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  result = (sfSoundStatus)sfSoundStream_getStatus((struct sfSoundStream const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_sfSoundStream_getChannelCount_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  result = (unsigned int)sfSoundStream_getChannelCount((struct sfSoundStream const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_sfSoundStream_getSampleRate_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  result = (unsigned int)sfSoundStream_getSampleRate((struct sfSoundStream const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_sfSoundStream_setPitch_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0, float _swig_go_1) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  float arg2 ;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  sfSoundStream_setPitch(arg1,arg2);
  
}


void _wrap_sfSoundStream_setVolume_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0, float _swig_go_1) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  float arg2 ;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  sfSoundStream_setVolume(arg1,arg2);
  
}


void _wrap_sfSoundStream_setPosition_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0, sfVector3f *_swig_go_1) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  sfVector3f arg2 ;
  sfVector3f *argp2 ;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  argp2 = (sfVector3f *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null sfVector3f");
  }
  arg2 = (sfVector3f)*argp2;
  
  
  sfSoundStream_setPosition(arg1,arg2);
  
}


void _wrap_sfSoundStream_setRelativeToListener_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0, intgo _swig_go_1) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  sfBool arg2 ;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  arg2 = (sfBool)_swig_go_1; 
  
  sfSoundStream_setRelativeToListener(arg1,arg2);
  
}


void _wrap_sfSoundStream_setMinDistance_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0, float _swig_go_1) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  float arg2 ;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  sfSoundStream_setMinDistance(arg1,arg2);
  
}


void _wrap_sfSoundStream_setAttenuation_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0, float _swig_go_1) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  float arg2 ;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  sfSoundStream_setAttenuation(arg1,arg2);
  
}


void _wrap_sfSoundStream_setPlayingOffset_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0, sfTime *_swig_go_1) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  sfTime arg2 ;
  sfTime *argp2 ;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  argp2 = (sfTime *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null sfTime");
  }
  arg2 = (sfTime)*argp2;
  
  
  sfSoundStream_setPlayingOffset(arg1,arg2);
  
}


void _wrap_sfSoundStream_setLoop_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0, intgo _swig_go_1) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  sfBool arg2 ;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  arg2 = (sfBool)_swig_go_1; 
  
  sfSoundStream_setLoop(arg1,arg2);
  
}


float _wrap_sfSoundStream_getPitch_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  result = (float)sfSoundStream_getPitch((struct sfSoundStream const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_sfSoundStream_getVolume_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  result = (float)sfSoundStream_getVolume((struct sfSoundStream const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


sfVector3f *_wrap_sfSoundStream_getPosition_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  sfVector3f result;
  sfVector3f *_swig_go_result;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  result = sfSoundStream_getPosition((struct sfSoundStream const *)arg1);
  {
    sfVector3f * resultptr = (sfVector3f *)malloc(sizeof(sfVector3f));
    memmove(resultptr, &result, sizeof(sfVector3f));
    *(sfVector3f **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


intgo _wrap_sfSoundStream_isRelativeToListener_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  sfBool result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  result = (sfBool)sfSoundStream_isRelativeToListener((struct sfSoundStream const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_sfSoundStream_getMinDistance_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  result = (float)sfSoundStream_getMinDistance((struct sfSoundStream const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_sfSoundStream_getAttenuation_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  result = (float)sfSoundStream_getAttenuation((struct sfSoundStream const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_sfSoundStream_getLoop_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  sfBool result;
  intgo _swig_go_result;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  result = (sfBool)sfSoundStream_getLoop((struct sfSoundStream const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


sfTime *_wrap_sfSoundStream_getPlayingOffset_audio_781f6cb27eac316e(struct sfSoundStream *_swig_go_0) {
  sfSoundStream *arg1 = (sfSoundStream *) 0 ;
  sfTime result;
  sfTime *_swig_go_result;
  
  arg1 = *(sfSoundStream **)&_swig_go_0; 
  
  result = sfSoundStream_getPlayingOffset((struct sfSoundStream const *)arg1);
  {
    sfTime * resultptr = (sfTime *)malloc(sizeof(sfTime));
    memmove(resultptr, &result, sizeof(sfTime));
    *(sfTime **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

