/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: /mnt/e/workspace/git/go-sfml/CSFML/include/SFML/Audio/Audio.i

package audio

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef long long swig_type_2;
typedef _gostring_ swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
typedef _gostring_ swig_type_6;
typedef long long swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef void* swig_type_10;
typedef void* swig_type_11;
typedef void* swig_type_12;
typedef _gostring_ swig_type_13;
typedef _gostring_ swig_type_14;
typedef _gostring_ swig_type_15;
typedef void* swig_type_16;
typedef void* swig_type_17;
extern void _wrap_Swig_free_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_audio_781f6cb27eac316e(swig_intgo arg1);
extern void _wrap_sfListener_setGlobalVolume_audio_781f6cb27eac316e(float arg1);
extern float _wrap_sfListener_getGlobalVolume_audio_781f6cb27eac316e(void);
extern void _wrap_sfListener_setPosition_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfListener_getPosition_audio_781f6cb27eac316e(void);
extern void _wrap_sfListener_setDirection_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfListener_getDirection_audio_781f6cb27eac316e(void);
extern void _wrap_sfListener_setUpVector_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfListener_getUpVector_audio_781f6cb27eac316e(void);
extern void _wrap_sfTimeSpan_offset_set_audio_781f6cb27eac316e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_sfTimeSpan_offset_get_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfTimeSpan_length_set_audio_781f6cb27eac316e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_sfTimeSpan_length_get_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_new_sfTimeSpan_audio_781f6cb27eac316e(void);
extern void _wrap_delete_sfTimeSpan_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfMusic_createFromFile_audio_781f6cb27eac316e(swig_type_1 arg1);
extern uintptr_t _wrap_sfMusic_createFromMemory_audio_781f6cb27eac316e(uintptr_t arg1, swig_type_2 arg2);
extern uintptr_t _wrap_sfMusic_createFromStream_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfMusic_destroy_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfMusic_setLoop_audio_781f6cb27eac316e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_sfMusic_getLoop_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfMusic_getDuration_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfMusic_getLoopPoints_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfMusic_setLoopPoints_audio_781f6cb27eac316e(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_sfMusic_play_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfMusic_pause_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfMusic_stop_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfMusic_getChannelCount_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfMusic_getSampleRate_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfMusic_getStatus_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfMusic_getPlayingOffset_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfMusic_setPitch_audio_781f6cb27eac316e(uintptr_t arg1, float arg2);
extern void _wrap_sfMusic_setVolume_audio_781f6cb27eac316e(uintptr_t arg1, float arg2);
extern void _wrap_sfMusic_setPosition_audio_781f6cb27eac316e(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_sfMusic_setRelativeToListener_audio_781f6cb27eac316e(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_sfMusic_setMinDistance_audio_781f6cb27eac316e(uintptr_t arg1, float arg2);
extern void _wrap_sfMusic_setAttenuation_audio_781f6cb27eac316e(uintptr_t arg1, float arg2);
extern void _wrap_sfMusic_setPlayingOffset_audio_781f6cb27eac316e(uintptr_t arg1, uintptr_t arg2);
extern float _wrap_sfMusic_getPitch_audio_781f6cb27eac316e(uintptr_t arg1);
extern float _wrap_sfMusic_getVolume_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfMusic_getPosition_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfMusic_isRelativeToListener_audio_781f6cb27eac316e(uintptr_t arg1);
extern float _wrap_sfMusic_getMinDistance_audio_781f6cb27eac316e(uintptr_t arg1);
extern float _wrap_sfMusic_getAttenuation_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfSound_create_audio_781f6cb27eac316e(void);
extern uintptr_t _wrap_sfSound_copy_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfSound_destroy_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfSound_play_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfSound_pause_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfSound_stop_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfSound_setBuffer_audio_781f6cb27eac316e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_sfSound_getBuffer_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfSound_setLoop_audio_781f6cb27eac316e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_sfSound_getLoop_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSound_getStatus_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfSound_setPitch_audio_781f6cb27eac316e(uintptr_t arg1, float arg2);
extern void _wrap_sfSound_setVolume_audio_781f6cb27eac316e(uintptr_t arg1, float arg2);
extern void _wrap_sfSound_setPosition_audio_781f6cb27eac316e(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_sfSound_setRelativeToListener_audio_781f6cb27eac316e(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_sfSound_setMinDistance_audio_781f6cb27eac316e(uintptr_t arg1, float arg2);
extern void _wrap_sfSound_setAttenuation_audio_781f6cb27eac316e(uintptr_t arg1, float arg2);
extern void _wrap_sfSound_setPlayingOffset_audio_781f6cb27eac316e(uintptr_t arg1, uintptr_t arg2);
extern float _wrap_sfSound_getPitch_audio_781f6cb27eac316e(uintptr_t arg1);
extern float _wrap_sfSound_getVolume_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfSound_getPosition_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSound_isRelativeToListener_audio_781f6cb27eac316e(uintptr_t arg1);
extern float _wrap_sfSound_getMinDistance_audio_781f6cb27eac316e(uintptr_t arg1);
extern float _wrap_sfSound_getAttenuation_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfSound_getPlayingOffset_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfSoundBuffer_createFromFile_audio_781f6cb27eac316e(swig_type_3 arg1);
extern uintptr_t _wrap_sfSoundBuffer_createFromMemory_audio_781f6cb27eac316e(uintptr_t arg1, swig_type_4 arg2);
extern uintptr_t _wrap_sfSoundBuffer_createFromStream_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfSoundBuffer_createFromSamples_audio_781f6cb27eac316e(swig_voidp arg1, swig_type_5 arg2, swig_intgo arg3, swig_intgo arg4);
extern uintptr_t _wrap_sfSoundBuffer_copy_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfSoundBuffer_destroy_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSoundBuffer_saveToFile_audio_781f6cb27eac316e(uintptr_t arg1, swig_type_6 arg2);
extern swig_voidp _wrap_sfSoundBuffer_getSamples_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_type_7 _wrap_sfSoundBuffer_getSampleCount_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSoundBuffer_getSampleRate_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSoundBuffer_getChannelCount_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfSoundBuffer_getDuration_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfSoundBufferRecorder_create_audio_781f6cb27eac316e(void);
extern void _wrap_sfSoundBufferRecorder_destroy_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSoundBufferRecorder_start_audio_781f6cb27eac316e(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_sfSoundBufferRecorder_stop_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSoundBufferRecorder_getSampleRate_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfSoundBufferRecorder_getBuffer_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSoundBufferRecorder_setDevice_audio_781f6cb27eac316e(uintptr_t arg1, swig_type_8 arg2);
extern swig_type_9 _wrap_sfSoundBufferRecorder_getDevice_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfSoundRecorder_create_audio_781f6cb27eac316e(swig_type_10 arg1, swig_type_11 arg2, swig_type_12 arg3, uintptr_t arg4);
extern void _wrap_sfSoundRecorder_destroy_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSoundRecorder_start_audio_781f6cb27eac316e(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_sfSoundRecorder_stop_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSoundRecorder_getSampleRate_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSoundRecorder_isAvailable_audio_781f6cb27eac316e(void);
extern void _wrap_sfSoundRecorder_setProcessingInterval_audio_781f6cb27eac316e(uintptr_t arg1, uintptr_t arg2);
extern swig_voidp _wrap_sfSoundRecorder_getAvailableDevices_audio_781f6cb27eac316e(swig_voidp arg1);
extern swig_type_13 _wrap_sfSoundRecorder_getDefaultDevice_audio_781f6cb27eac316e(void);
extern swig_intgo _wrap_sfSoundRecorder_setDevice_audio_781f6cb27eac316e(uintptr_t arg1, swig_type_14 arg2);
extern swig_type_15 _wrap_sfSoundRecorder_getDevice_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfSoundRecorder_setChannelCount_audio_781f6cb27eac316e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_sfSoundRecorder_getChannelCount_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfStopped_audio_781f6cb27eac316e(void);
extern swig_intgo _wrap_sfPaused_audio_781f6cb27eac316e(void);
extern swig_intgo _wrap_sfPlaying_audio_781f6cb27eac316e(void);
extern void _wrap_sfSoundStreamChunk_samples_set_audio_781f6cb27eac316e(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_sfSoundStreamChunk_samples_get_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfSoundStreamChunk_sampleCount_set_audio_781f6cb27eac316e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_sfSoundStreamChunk_sampleCount_get_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_new_sfSoundStreamChunk_audio_781f6cb27eac316e(void);
extern void _wrap_delete_sfSoundStreamChunk_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfSoundStream_create_audio_781f6cb27eac316e(swig_type_16 arg1, swig_type_17 arg2, swig_intgo arg3, swig_intgo arg4, uintptr_t arg5);
extern void _wrap_sfSoundStream_destroy_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfSoundStream_play_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfSoundStream_pause_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfSoundStream_stop_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSoundStream_getStatus_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSoundStream_getChannelCount_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSoundStream_getSampleRate_audio_781f6cb27eac316e(uintptr_t arg1);
extern void _wrap_sfSoundStream_setPitch_audio_781f6cb27eac316e(uintptr_t arg1, float arg2);
extern void _wrap_sfSoundStream_setVolume_audio_781f6cb27eac316e(uintptr_t arg1, float arg2);
extern void _wrap_sfSoundStream_setPosition_audio_781f6cb27eac316e(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_sfSoundStream_setRelativeToListener_audio_781f6cb27eac316e(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_sfSoundStream_setMinDistance_audio_781f6cb27eac316e(uintptr_t arg1, float arg2);
extern void _wrap_sfSoundStream_setAttenuation_audio_781f6cb27eac316e(uintptr_t arg1, float arg2);
extern void _wrap_sfSoundStream_setPlayingOffset_audio_781f6cb27eac316e(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_sfSoundStream_setLoop_audio_781f6cb27eac316e(uintptr_t arg1, swig_intgo arg2);
extern float _wrap_sfSoundStream_getPitch_audio_781f6cb27eac316e(uintptr_t arg1);
extern float _wrap_sfSoundStream_getVolume_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfSoundStream_getPosition_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSoundStream_isRelativeToListener_audio_781f6cb27eac316e(uintptr_t arg1);
extern float _wrap_sfSoundStream_getMinDistance_audio_781f6cb27eac316e(uintptr_t arg1);
extern float _wrap_sfSoundStream_getAttenuation_audio_781f6cb27eac316e(uintptr_t arg1);
extern swig_intgo _wrap_sfSoundStream_getLoop_audio_781f6cb27eac316e(uintptr_t arg1);
extern uintptr_t _wrap_sfSoundStream_getPlayingOffset_audio_781f6cb27eac316e(uintptr_t arg1);
#undef intgo
*/
// #cgo LDFLAGS: -lcsfml-audio
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_audio_781f6cb27eac316e(C.swig_intgo(_swig_i_0)))
	return swig_r
}

const CSFML_VERSION_MAJOR int = 2
const CSFML_VERSION_MINOR int = 5
const CSFML_VERSION_PATCH int = 1
const SfFalse int = 0
const SfTrue int = 1
func SfListener_setGlobalVolume(arg1 float32) {
	_swig_i_0 := arg1
	C._wrap_sfListener_setGlobalVolume_audio_781f6cb27eac316e(C.float(_swig_i_0))
}

func SfListener_getGlobalVolume() (_swig_ret float32) {
	var swig_r float32
	swig_r = (float32)(C._wrap_sfListener_getGlobalVolume_audio_781f6cb27eac316e())
	return swig_r
}

func SfListener_setPosition(arg1 SfVector3f) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfListener_setPosition_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfListener_getPosition() (_swig_ret SfVector3f) {
	var swig_r SfVector3f
	swig_r = (SfVector3f)(SwigcptrSfVector3f(C._wrap_sfListener_getPosition_audio_781f6cb27eac316e()))
	return swig_r
}

func SfListener_setDirection(arg1 SfVector3f) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfListener_setDirection_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfListener_getDirection() (_swig_ret SfVector3f) {
	var swig_r SfVector3f
	swig_r = (SfVector3f)(SwigcptrSfVector3f(C._wrap_sfListener_getDirection_audio_781f6cb27eac316e()))
	return swig_r
}

func SfListener_setUpVector(arg1 SfVector3f) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfListener_setUpVector_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfListener_getUpVector() (_swig_ret SfVector3f) {
	var swig_r SfVector3f
	swig_r = (SfVector3f)(SwigcptrSfVector3f(C._wrap_sfListener_getUpVector_audio_781f6cb27eac316e()))
	return swig_r
}

type SwigcptrSfTimeSpan uintptr

func (p SwigcptrSfTimeSpan) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSfTimeSpan) SwigIsSfTimeSpan() {
}

func (arg1 SwigcptrSfTimeSpan) SetOffset(arg2 SfTime) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_sfTimeSpan_offset_set_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrSfTimeSpan) GetOffset() (_swig_ret SfTime) {
	var swig_r SfTime
	_swig_i_0 := arg1
	swig_r = (SfTime)(SwigcptrSfTime(C._wrap_sfTimeSpan_offset_get_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrSfTimeSpan) SetLength(arg2 SfTime) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_sfTimeSpan_length_set_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrSfTimeSpan) GetLength() (_swig_ret SfTime) {
	var swig_r SfTime
	_swig_i_0 := arg1
	swig_r = (SfTime)(SwigcptrSfTime(C._wrap_sfTimeSpan_length_get_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewSfTimeSpan() (_swig_ret SfTimeSpan) {
	var swig_r SfTimeSpan
	swig_r = (SfTimeSpan)(SwigcptrSfTimeSpan(C._wrap_new_sfTimeSpan_audio_781f6cb27eac316e()))
	return swig_r
}

func DeleteSfTimeSpan(arg1 SfTimeSpan) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_sfTimeSpan_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

type SfTimeSpan interface {
	Swigcptr() uintptr
	SwigIsSfTimeSpan()
	SetOffset(arg2 SfTime)
	GetOffset() (_swig_ret SfTime)
	SetLength(arg2 SfTime)
	GetLength() (_swig_ret SfTime)
}

func SfMusic_createFromFile(arg1 string) (_swig_ret Struct_SS_sfMusic) {
	var swig_r Struct_SS_sfMusic
	_swig_i_0 := arg1
	swig_r = (Struct_SS_sfMusic)(SwigcptrStruct_SS_sfMusic(C._wrap_sfMusic_createFromFile_audio_781f6cb27eac316e(*(*C.swig_type_1)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func SfMusic_createFromMemory(arg1 uintptr, arg2 int64) (_swig_ret Struct_SS_sfMusic) {
	var swig_r Struct_SS_sfMusic
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Struct_SS_sfMusic)(SwigcptrStruct_SS_sfMusic(C._wrap_sfMusic_createFromMemory_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.swig_type_2(_swig_i_1))))
	return swig_r
}

func SfMusic_createFromStream(arg1 SfInputStream) (_swig_ret Struct_SS_sfMusic) {
	var swig_r Struct_SS_sfMusic
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_sfMusic)(SwigcptrStruct_SS_sfMusic(C._wrap_sfMusic_createFromStream_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfMusic_destroy(arg1 Struct_SS_sfMusic) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfMusic_destroy_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfMusic_setLoop(arg1 Struct_SS_sfMusic, arg2 int) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfMusic_setLoop_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func SfMusic_getLoop(arg1 Struct_SS_sfMusic) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_sfMusic_getLoop_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfMusic_getDuration(arg1 Struct_SS_sfMusic) (_swig_ret SfTime) {
	var swig_r SfTime
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (SfTime)(SwigcptrSfTime(C._wrap_sfMusic_getDuration_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfMusic_getLoopPoints(arg1 Struct_SS_sfMusic) (_swig_ret SfTimeSpan) {
	var swig_r SfTimeSpan
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (SfTimeSpan)(SwigcptrSfTimeSpan(C._wrap_sfMusic_getLoopPoints_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfMusic_setLoopPoints(arg1 Struct_SS_sfMusic, arg2 SfTimeSpan) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_sfMusic_setLoopPoints_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func SfMusic_play(arg1 Struct_SS_sfMusic) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfMusic_play_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfMusic_pause(arg1 Struct_SS_sfMusic) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfMusic_pause_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfMusic_stop(arg1 Struct_SS_sfMusic) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfMusic_stop_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfMusic_getChannelCount(arg1 Struct_SS_sfMusic) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint)(C._wrap_sfMusic_getChannelCount_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfMusic_getSampleRate(arg1 Struct_SS_sfMusic) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint)(C._wrap_sfMusic_getSampleRate_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfMusic_getStatus(arg1 Struct_SS_sfMusic) (_swig_ret SfSoundStatus) {
	var swig_r SfSoundStatus
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (SfSoundStatus)(C._wrap_sfMusic_getStatus_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfMusic_getPlayingOffset(arg1 Struct_SS_sfMusic) (_swig_ret SfTime) {
	var swig_r SfTime
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (SfTime)(SwigcptrSfTime(C._wrap_sfMusic_getPlayingOffset_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfMusic_setPitch(arg1 Struct_SS_sfMusic, arg2 float32) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfMusic_setPitch_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func SfMusic_setVolume(arg1 Struct_SS_sfMusic, arg2 float32) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfMusic_setVolume_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func SfMusic_setPosition(arg1 Struct_SS_sfMusic, arg2 SfVector3f) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_sfMusic_setPosition_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func SfMusic_setRelativeToListener(arg1 Struct_SS_sfMusic, arg2 int) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfMusic_setRelativeToListener_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func SfMusic_setMinDistance(arg1 Struct_SS_sfMusic, arg2 float32) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfMusic_setMinDistance_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func SfMusic_setAttenuation(arg1 Struct_SS_sfMusic, arg2 float32) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfMusic_setAttenuation_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func SfMusic_setPlayingOffset(arg1 Struct_SS_sfMusic, arg2 SfTime) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_sfMusic_setPlayingOffset_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func SfMusic_getPitch(arg1 Struct_SS_sfMusic) (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (float32)(C._wrap_sfMusic_getPitch_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfMusic_getVolume(arg1 Struct_SS_sfMusic) (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (float32)(C._wrap_sfMusic_getVolume_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfMusic_getPosition(arg1 Struct_SS_sfMusic) (_swig_ret SfVector3f) {
	var swig_r SfVector3f
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (SfVector3f)(SwigcptrSfVector3f(C._wrap_sfMusic_getPosition_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfMusic_isRelativeToListener(arg1 Struct_SS_sfMusic) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_sfMusic_isRelativeToListener_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfMusic_getMinDistance(arg1 Struct_SS_sfMusic) (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (float32)(C._wrap_sfMusic_getMinDistance_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfMusic_getAttenuation(arg1 Struct_SS_sfMusic) (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (float32)(C._wrap_sfMusic_getAttenuation_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSound_create() (_swig_ret Struct_SS_sfSound) {
	var swig_r Struct_SS_sfSound
	swig_r = (Struct_SS_sfSound)(SwigcptrStruct_SS_sfSound(C._wrap_sfSound_create_audio_781f6cb27eac316e()))
	return swig_r
}

func SfSound_copy(arg1 Struct_SS_sfSound) (_swig_ret Struct_SS_sfSound) {
	var swig_r Struct_SS_sfSound
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_sfSound)(SwigcptrStruct_SS_sfSound(C._wrap_sfSound_copy_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfSound_destroy(arg1 Struct_SS_sfSound) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfSound_destroy_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfSound_play(arg1 Struct_SS_sfSound) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfSound_play_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfSound_pause(arg1 Struct_SS_sfSound) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfSound_pause_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfSound_stop(arg1 Struct_SS_sfSound) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfSound_stop_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfSound_setBuffer(arg1 Struct_SS_sfSound, arg2 Struct_SS_sfSoundBuffer) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_sfSound_setBuffer_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func SfSound_getBuffer(arg1 Struct_SS_sfSound) (_swig_ret Struct_SS_sfSoundBuffer) {
	var swig_r Struct_SS_sfSoundBuffer
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_sfSoundBuffer)(SwigcptrStruct_SS_sfSoundBuffer(C._wrap_sfSound_getBuffer_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfSound_setLoop(arg1 Struct_SS_sfSound, arg2 int) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfSound_setLoop_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func SfSound_getLoop(arg1 Struct_SS_sfSound) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_sfSound_getLoop_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSound_getStatus(arg1 Struct_SS_sfSound) (_swig_ret SfSoundStatus) {
	var swig_r SfSoundStatus
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (SfSoundStatus)(C._wrap_sfSound_getStatus_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSound_setPitch(arg1 Struct_SS_sfSound, arg2 float32) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfSound_setPitch_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func SfSound_setVolume(arg1 Struct_SS_sfSound, arg2 float32) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfSound_setVolume_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func SfSound_setPosition(arg1 Struct_SS_sfSound, arg2 SfVector3f) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_sfSound_setPosition_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func SfSound_setRelativeToListener(arg1 Struct_SS_sfSound, arg2 int) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfSound_setRelativeToListener_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func SfSound_setMinDistance(arg1 Struct_SS_sfSound, arg2 float32) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfSound_setMinDistance_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func SfSound_setAttenuation(arg1 Struct_SS_sfSound, arg2 float32) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfSound_setAttenuation_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func SfSound_setPlayingOffset(arg1 Struct_SS_sfSound, arg2 SfTime) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_sfSound_setPlayingOffset_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func SfSound_getPitch(arg1 Struct_SS_sfSound) (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (float32)(C._wrap_sfSound_getPitch_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSound_getVolume(arg1 Struct_SS_sfSound) (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (float32)(C._wrap_sfSound_getVolume_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSound_getPosition(arg1 Struct_SS_sfSound) (_swig_ret SfVector3f) {
	var swig_r SfVector3f
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (SfVector3f)(SwigcptrSfVector3f(C._wrap_sfSound_getPosition_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfSound_isRelativeToListener(arg1 Struct_SS_sfSound) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_sfSound_isRelativeToListener_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSound_getMinDistance(arg1 Struct_SS_sfSound) (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (float32)(C._wrap_sfSound_getMinDistance_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSound_getAttenuation(arg1 Struct_SS_sfSound) (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (float32)(C._wrap_sfSound_getAttenuation_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSound_getPlayingOffset(arg1 Struct_SS_sfSound) (_swig_ret SfTime) {
	var swig_r SfTime
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (SfTime)(SwigcptrSfTime(C._wrap_sfSound_getPlayingOffset_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfSoundBuffer_createFromFile(arg1 string) (_swig_ret Struct_SS_sfSoundBuffer) {
	var swig_r Struct_SS_sfSoundBuffer
	_swig_i_0 := arg1
	swig_r = (Struct_SS_sfSoundBuffer)(SwigcptrStruct_SS_sfSoundBuffer(C._wrap_sfSoundBuffer_createFromFile_audio_781f6cb27eac316e(*(*C.swig_type_3)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func SfSoundBuffer_createFromMemory(arg1 uintptr, arg2 int64) (_swig_ret Struct_SS_sfSoundBuffer) {
	var swig_r Struct_SS_sfSoundBuffer
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Struct_SS_sfSoundBuffer)(SwigcptrStruct_SS_sfSoundBuffer(C._wrap_sfSoundBuffer_createFromMemory_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.swig_type_4(_swig_i_1))))
	return swig_r
}

func SfSoundBuffer_createFromStream(arg1 SfInputStream) (_swig_ret Struct_SS_sfSoundBuffer) {
	var swig_r Struct_SS_sfSoundBuffer
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_sfSoundBuffer)(SwigcptrStruct_SS_sfSoundBuffer(C._wrap_sfSoundBuffer_createFromStream_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfSoundBuffer_createFromSamples(arg1 *int16, arg2 uint64, arg3 uint, arg4 uint) (_swig_ret Struct_SS_sfSoundBuffer) {
	var swig_r Struct_SS_sfSoundBuffer
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (Struct_SS_sfSoundBuffer)(SwigcptrStruct_SS_sfSoundBuffer(C._wrap_sfSoundBuffer_createFromSamples_audio_781f6cb27eac316e(C.swig_voidp(_swig_i_0), C.swig_type_5(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3))))
	return swig_r
}

func SfSoundBuffer_copy(arg1 Struct_SS_sfSoundBuffer) (_swig_ret Struct_SS_sfSoundBuffer) {
	var swig_r Struct_SS_sfSoundBuffer
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_sfSoundBuffer)(SwigcptrStruct_SS_sfSoundBuffer(C._wrap_sfSoundBuffer_copy_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfSoundBuffer_destroy(arg1 Struct_SS_sfSoundBuffer) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfSoundBuffer_destroy_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfSoundBuffer_saveToFile(arg1 Struct_SS_sfSoundBuffer, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_sfSoundBuffer_saveToFile_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func SfSoundBuffer_getSamples(arg1 Struct_SS_sfSoundBuffer) (_swig_ret *int16) {
	var swig_r *int16
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (*int16)(C._wrap_sfSoundBuffer_getSamples_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSoundBuffer_getSampleCount(arg1 Struct_SS_sfSoundBuffer) (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint64)(C._wrap_sfSoundBuffer_getSampleCount_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSoundBuffer_getSampleRate(arg1 Struct_SS_sfSoundBuffer) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint)(C._wrap_sfSoundBuffer_getSampleRate_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSoundBuffer_getChannelCount(arg1 Struct_SS_sfSoundBuffer) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint)(C._wrap_sfSoundBuffer_getChannelCount_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSoundBuffer_getDuration(arg1 Struct_SS_sfSoundBuffer) (_swig_ret SfTime) {
	var swig_r SfTime
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (SfTime)(SwigcptrSfTime(C._wrap_sfSoundBuffer_getDuration_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfSoundBufferRecorder_create() (_swig_ret Struct_SS_sfSoundBufferRecorder) {
	var swig_r Struct_SS_sfSoundBufferRecorder
	swig_r = (Struct_SS_sfSoundBufferRecorder)(SwigcptrStruct_SS_sfSoundBufferRecorder(C._wrap_sfSoundBufferRecorder_create_audio_781f6cb27eac316e()))
	return swig_r
}

func SfSoundBufferRecorder_destroy(arg1 Struct_SS_sfSoundBufferRecorder) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfSoundBufferRecorder_destroy_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfSoundBufferRecorder_start(arg1 Struct_SS_sfSoundBufferRecorder, arg2 uint) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_sfSoundBufferRecorder_start_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func SfSoundBufferRecorder_stop(arg1 Struct_SS_sfSoundBufferRecorder) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfSoundBufferRecorder_stop_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfSoundBufferRecorder_getSampleRate(arg1 Struct_SS_sfSoundBufferRecorder) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint)(C._wrap_sfSoundBufferRecorder_getSampleRate_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSoundBufferRecorder_getBuffer(arg1 Struct_SS_sfSoundBufferRecorder) (_swig_ret Struct_SS_sfSoundBuffer) {
	var swig_r Struct_SS_sfSoundBuffer
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_sfSoundBuffer)(SwigcptrStruct_SS_sfSoundBuffer(C._wrap_sfSoundBufferRecorder_getBuffer_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfSoundBufferRecorder_setDevice(arg1 Struct_SS_sfSoundBufferRecorder, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_sfSoundBufferRecorder_setDevice_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), *(*C.swig_type_8)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func SfSoundBufferRecorder_getDevice(arg1 Struct_SS_sfSoundBufferRecorder) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_sfSoundBufferRecorder_getDevice_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func SfSoundRecorder_create(arg1 _swig_fnptr, arg2 _swig_fnptr, arg3 _swig_fnptr, arg4 uintptr) (_swig_ret Struct_SS_sfSoundRecorder) {
	var swig_r Struct_SS_sfSoundRecorder
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (Struct_SS_sfSoundRecorder)(SwigcptrStruct_SS_sfSoundRecorder(C._wrap_sfSoundRecorder_create_audio_781f6cb27eac316e(C.swig_type_10(_swig_i_0), C.swig_type_11(_swig_i_1), C.swig_type_12(_swig_i_2), C.uintptr_t(_swig_i_3))))
	return swig_r
}

func SfSoundRecorder_destroy(arg1 Struct_SS_sfSoundRecorder) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfSoundRecorder_destroy_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfSoundRecorder_start(arg1 Struct_SS_sfSoundRecorder, arg2 uint) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_sfSoundRecorder_start_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func SfSoundRecorder_stop(arg1 Struct_SS_sfSoundRecorder) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfSoundRecorder_stop_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfSoundRecorder_getSampleRate(arg1 Struct_SS_sfSoundRecorder) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint)(C._wrap_sfSoundRecorder_getSampleRate_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSoundRecorder_isAvailable() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_sfSoundRecorder_isAvailable_audio_781f6cb27eac316e())
	return swig_r
}

func SfSoundRecorder_setProcessingInterval(arg1 Struct_SS_sfSoundRecorder, arg2 SfTime) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_sfSoundRecorder_setProcessingInterval_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func SfSoundRecorder_getAvailableDevices(arg1 *int64) (_swig_ret *string) {
	var swig_r *string
	_swig_i_0 := arg1
	swig_r = (*string)(C._wrap_sfSoundRecorder_getAvailableDevices_audio_781f6cb27eac316e(C.swig_voidp(_swig_i_0)))
	return swig_r
}

func SfSoundRecorder_getDefaultDevice() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_sfSoundRecorder_getDefaultDevice_audio_781f6cb27eac316e()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func SfSoundRecorder_setDevice(arg1 Struct_SS_sfSoundRecorder, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_sfSoundRecorder_setDevice_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), *(*C.swig_type_14)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func SfSoundRecorder_getDevice(arg1 Struct_SS_sfSoundRecorder) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_sfSoundRecorder_getDevice_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func SfSoundRecorder_setChannelCount(arg1 Struct_SS_sfSoundRecorder, arg2 uint) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfSoundRecorder_setChannelCount_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func SfSoundRecorder_getChannelCount(arg1 Struct_SS_sfSoundRecorder) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint)(C._wrap_sfSoundRecorder_getChannelCount_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

type SfSoundStatus int
func _swig_getsfStopped() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_sfStopped_audio_781f6cb27eac316e())
	return swig_r
}

var SfStopped int = _swig_getsfStopped()
func _swig_getsfPaused() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_sfPaused_audio_781f6cb27eac316e())
	return swig_r
}

var SfPaused int = _swig_getsfPaused()
func _swig_getsfPlaying() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_sfPlaying_audio_781f6cb27eac316e())
	return swig_r
}

var SfPlaying int = _swig_getsfPlaying()
type SwigcptrSfSoundStreamChunk uintptr

func (p SwigcptrSfSoundStreamChunk) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSfSoundStreamChunk) SwigIsSfSoundStreamChunk() {
}

func (arg1 SwigcptrSfSoundStreamChunk) SetSamples(arg2 *int16) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfSoundStreamChunk_samples_set_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrSfSoundStreamChunk) GetSamples() (_swig_ret *int16) {
	var swig_r *int16
	_swig_i_0 := arg1
	swig_r = (*int16)(C._wrap_sfSoundStreamChunk_samples_get_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSfSoundStreamChunk) SetSampleCount(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfSoundStreamChunk_sampleCount_set_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrSfSoundStreamChunk) GetSampleCount() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_sfSoundStreamChunk_sampleCount_get_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewSfSoundStreamChunk() (_swig_ret SfSoundStreamChunk) {
	var swig_r SfSoundStreamChunk
	swig_r = (SfSoundStreamChunk)(SwigcptrSfSoundStreamChunk(C._wrap_new_sfSoundStreamChunk_audio_781f6cb27eac316e()))
	return swig_r
}

func DeleteSfSoundStreamChunk(arg1 SfSoundStreamChunk) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_sfSoundStreamChunk_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

type SfSoundStreamChunk interface {
	Swigcptr() uintptr
	SwigIsSfSoundStreamChunk()
	SetSamples(arg2 *int16)
	GetSamples() (_swig_ret *int16)
	SetSampleCount(arg2 uint)
	GetSampleCount() (_swig_ret uint)
}

func SfSoundStream_create(arg1 _swig_fnptr, arg2 _swig_fnptr, arg3 uint, arg4 uint, arg5 uintptr) (_swig_ret Struct_SS_sfSoundStream) {
	var swig_r Struct_SS_sfSoundStream
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (Struct_SS_sfSoundStream)(SwigcptrStruct_SS_sfSoundStream(C._wrap_sfSoundStream_create_audio_781f6cb27eac316e(C.swig_type_16(_swig_i_0), C.swig_type_17(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.uintptr_t(_swig_i_4))))
	return swig_r
}

func SfSoundStream_destroy(arg1 Struct_SS_sfSoundStream) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfSoundStream_destroy_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfSoundStream_play(arg1 Struct_SS_sfSoundStream) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfSoundStream_play_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfSoundStream_pause(arg1 Struct_SS_sfSoundStream) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfSoundStream_pause_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfSoundStream_stop(arg1 Struct_SS_sfSoundStream) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfSoundStream_stop_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))
}

func SfSoundStream_getStatus(arg1 Struct_SS_sfSoundStream) (_swig_ret SfSoundStatus) {
	var swig_r SfSoundStatus
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (SfSoundStatus)(C._wrap_sfSoundStream_getStatus_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSoundStream_getChannelCount(arg1 Struct_SS_sfSoundStream) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint)(C._wrap_sfSoundStream_getChannelCount_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSoundStream_getSampleRate(arg1 Struct_SS_sfSoundStream) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint)(C._wrap_sfSoundStream_getSampleRate_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSoundStream_setPitch(arg1 Struct_SS_sfSoundStream, arg2 float32) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfSoundStream_setPitch_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func SfSoundStream_setVolume(arg1 Struct_SS_sfSoundStream, arg2 float32) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfSoundStream_setVolume_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func SfSoundStream_setPosition(arg1 Struct_SS_sfSoundStream, arg2 SfVector3f) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_sfSoundStream_setPosition_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func SfSoundStream_setRelativeToListener(arg1 Struct_SS_sfSoundStream, arg2 int) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfSoundStream_setRelativeToListener_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func SfSoundStream_setMinDistance(arg1 Struct_SS_sfSoundStream, arg2 float32) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfSoundStream_setMinDistance_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func SfSoundStream_setAttenuation(arg1 Struct_SS_sfSoundStream, arg2 float32) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfSoundStream_setAttenuation_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func SfSoundStream_setPlayingOffset(arg1 Struct_SS_sfSoundStream, arg2 SfTime) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_sfSoundStream_setPlayingOffset_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func SfSoundStream_setLoop(arg1 Struct_SS_sfSoundStream, arg2 int) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_sfSoundStream_setLoop_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func SfSoundStream_getPitch(arg1 Struct_SS_sfSoundStream) (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (float32)(C._wrap_sfSoundStream_getPitch_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSoundStream_getVolume(arg1 Struct_SS_sfSoundStream) (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (float32)(C._wrap_sfSoundStream_getVolume_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSoundStream_getPosition(arg1 Struct_SS_sfSoundStream) (_swig_ret SfVector3f) {
	var swig_r SfVector3f
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (SfVector3f)(SwigcptrSfVector3f(C._wrap_sfSoundStream_getPosition_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfSoundStream_isRelativeToListener(arg1 Struct_SS_sfSoundStream) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_sfSoundStream_isRelativeToListener_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSoundStream_getMinDistance(arg1 Struct_SS_sfSoundStream) (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (float32)(C._wrap_sfSoundStream_getMinDistance_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSoundStream_getAttenuation(arg1 Struct_SS_sfSoundStream) (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (float32)(C._wrap_sfSoundStream_getAttenuation_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSoundStream_getLoop(arg1 Struct_SS_sfSoundStream) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_sfSoundStream_getLoop_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSoundStream_getPlayingOffset(arg1 Struct_SS_sfSoundStream) (_swig_ret SfTime) {
	var swig_r SfTime
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (SfTime)(SwigcptrSfTime(C._wrap_sfSoundStream_getPlayingOffset_audio_781f6cb27eac316e(C.uintptr_t(_swig_i_0))))
	return swig_r
}


type SwigcptrStruct_SS_sfSoundBuffer uintptr
type Struct_SS_sfSoundBuffer interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_sfSoundBuffer) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_sfSoundBufferRecorder uintptr
type Struct_SS_sfSoundBufferRecorder interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_sfSoundBufferRecorder) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_sfSoundRecorder uintptr
type Struct_SS_sfSoundRecorder interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_sfSoundRecorder) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrSfVector3f uintptr
type SfVector3f interface {
	Swigcptr() uintptr;
}
func (p SwigcptrSfVector3f) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_sfMusic uintptr
type Struct_SS_sfMusic interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_sfMusic) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrSfTime uintptr
type SfTime interface {
	Swigcptr() uintptr;
}
func (p SwigcptrSfTime) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_sfSound uintptr
type Struct_SS_sfSound interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_sfSound) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrSfInputStream uintptr
type SfInputStream interface {
	Swigcptr() uintptr;
}
func (p SwigcptrSfInputStream) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_sfSoundStream uintptr
type Struct_SS_sfSoundStream interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_sfSoundStream) Swigcptr() uintptr {
	return uintptr(p)
}

