/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: /Users/cmc/dev/go_workspace/src/github.com/teh-cmc/go-sfml/CSFML/include/SFML/System/System.i

package system

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_system_ff5467e5aa4f17e8(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_system_ff5467e5aa4f17e8(swig_intgo arg1);
extern void _wrap_sfVector2i_x_set_system_ff5467e5aa4f17e8(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_sfVector2i_x_get_system_ff5467e5aa4f17e8(uintptr_t arg1);
extern void _wrap_sfVector2i_y_set_system_ff5467e5aa4f17e8(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_sfVector2i_y_get_system_ff5467e5aa4f17e8(uintptr_t arg1);
extern uintptr_t _wrap_new_sfVector2i_system_ff5467e5aa4f17e8(void);
extern void _wrap_delete_sfVector2i_system_ff5467e5aa4f17e8(uintptr_t arg1);
extern void _wrap_sfVector2u_x_set_system_ff5467e5aa4f17e8(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_sfVector2u_x_get_system_ff5467e5aa4f17e8(uintptr_t arg1);
extern void _wrap_sfVector2u_y_set_system_ff5467e5aa4f17e8(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_sfVector2u_y_get_system_ff5467e5aa4f17e8(uintptr_t arg1);
extern uintptr_t _wrap_new_sfVector2u_system_ff5467e5aa4f17e8(void);
extern void _wrap_delete_sfVector2u_system_ff5467e5aa4f17e8(uintptr_t arg1);
extern void _wrap_sfVector2f_x_set_system_ff5467e5aa4f17e8(uintptr_t arg1, float arg2);
extern float _wrap_sfVector2f_x_get_system_ff5467e5aa4f17e8(uintptr_t arg1);
extern void _wrap_sfVector2f_y_set_system_ff5467e5aa4f17e8(uintptr_t arg1, float arg2);
extern float _wrap_sfVector2f_y_get_system_ff5467e5aa4f17e8(uintptr_t arg1);
extern uintptr_t _wrap_new_sfVector2f_system_ff5467e5aa4f17e8(void);
extern void _wrap_delete_sfVector2f_system_ff5467e5aa4f17e8(uintptr_t arg1);
extern void _wrap_sfVector3f_x_set_system_ff5467e5aa4f17e8(uintptr_t arg1, float arg2);
extern float _wrap_sfVector3f_x_get_system_ff5467e5aa4f17e8(uintptr_t arg1);
extern void _wrap_sfVector3f_y_set_system_ff5467e5aa4f17e8(uintptr_t arg1, float arg2);
extern float _wrap_sfVector3f_y_get_system_ff5467e5aa4f17e8(uintptr_t arg1);
extern void _wrap_sfVector3f_z_set_system_ff5467e5aa4f17e8(uintptr_t arg1, float arg2);
extern float _wrap_sfVector3f_z_get_system_ff5467e5aa4f17e8(uintptr_t arg1);
extern uintptr_t _wrap_new_sfVector3f_system_ff5467e5aa4f17e8(void);
extern void _wrap_delete_sfVector3f_system_ff5467e5aa4f17e8(uintptr_t arg1);
#undef intgo
*/
// #cgo LDFLAGS: -lcsfml-system
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_system_ff5467e5aa4f17e8(C.swig_intgo(_swig_i_0)))
	return swig_r
}

const CSFML_VERSION_MAJOR int = 2
const CSFML_VERSION_MINOR int = 4
const CSFML_VERSION_PATCH int = 0
const SfFalse int = 0
const SfTrue int = 1
type SwigcptrSfVector2i uintptr

func (p SwigcptrSfVector2i) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSfVector2i) SwigIsSfVector2i() {
}

func (arg1 SwigcptrSfVector2i) SetX(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector2i_x_set_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrSfVector2i) GetX() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_sfVector2i_x_get_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSfVector2i) SetY(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector2i_y_set_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrSfVector2i) GetY() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_sfVector2i_y_get_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewSfVector2i() (_swig_ret SfVector2i) {
	var swig_r SfVector2i
	swig_r = (SfVector2i)(SwigcptrSfVector2i(C._wrap_new_sfVector2i_system_ff5467e5aa4f17e8()))
	return swig_r
}

func DeleteSfVector2i(arg1 SfVector2i) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_sfVector2i_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0))
}

type SfVector2i interface {
	Swigcptr() uintptr
	SwigIsSfVector2i()
	SetX(arg2 int)
	GetX() (_swig_ret int)
	SetY(arg2 int)
	GetY() (_swig_ret int)
}

type SwigcptrSfVector2u uintptr

func (p SwigcptrSfVector2u) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSfVector2u) SwigIsSfVector2u() {
}

func (arg1 SwigcptrSfVector2u) SetX(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector2u_x_set_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrSfVector2u) GetX() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_sfVector2u_x_get_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSfVector2u) SetY(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector2u_y_set_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrSfVector2u) GetY() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_sfVector2u_y_get_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewSfVector2u() (_swig_ret SfVector2u) {
	var swig_r SfVector2u
	swig_r = (SfVector2u)(SwigcptrSfVector2u(C._wrap_new_sfVector2u_system_ff5467e5aa4f17e8()))
	return swig_r
}

func DeleteSfVector2u(arg1 SfVector2u) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_sfVector2u_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0))
}

type SfVector2u interface {
	Swigcptr() uintptr
	SwigIsSfVector2u()
	SetX(arg2 uint)
	GetX() (_swig_ret uint)
	SetY(arg2 uint)
	GetY() (_swig_ret uint)
}

type SwigcptrSfVector2f uintptr

func (p SwigcptrSfVector2f) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSfVector2f) SwigIsSfVector2f() {
}

func (arg1 SwigcptrSfVector2f) SetX(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector2f_x_set_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrSfVector2f) GetX() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_sfVector2f_x_get_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSfVector2f) SetY(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector2f_y_set_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrSfVector2f) GetY() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_sfVector2f_y_get_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewSfVector2f() (_swig_ret SfVector2f) {
	var swig_r SfVector2f
	swig_r = (SfVector2f)(SwigcptrSfVector2f(C._wrap_new_sfVector2f_system_ff5467e5aa4f17e8()))
	return swig_r
}

func DeleteSfVector2f(arg1 SfVector2f) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_sfVector2f_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0))
}

type SfVector2f interface {
	Swigcptr() uintptr
	SwigIsSfVector2f()
	SetX(arg2 float32)
	GetX() (_swig_ret float32)
	SetY(arg2 float32)
	GetY() (_swig_ret float32)
}

type SwigcptrSfVector3f uintptr

func (p SwigcptrSfVector3f) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSfVector3f) SwigIsSfVector3f() {
}

func (arg1 SwigcptrSfVector3f) SetX(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector3f_x_set_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrSfVector3f) GetX() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_sfVector3f_x_get_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSfVector3f) SetY(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector3f_y_set_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrSfVector3f) GetY() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_sfVector3f_y_get_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSfVector3f) SetZ(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector3f_z_set_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrSfVector3f) GetZ() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_sfVector3f_z_get_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewSfVector3f() (_swig_ret SfVector3f) {
	var swig_r SfVector3f
	swig_r = (SfVector3f)(SwigcptrSfVector3f(C._wrap_new_sfVector3f_system_ff5467e5aa4f17e8()))
	return swig_r
}

func DeleteSfVector3f(arg1 SfVector3f) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_sfVector3f_system_ff5467e5aa4f17e8(C.uintptr_t(_swig_i_0))
}

type SfVector3f interface {
	Swigcptr() uintptr
	SwigIsSfVector3f()
	SetX(arg2 float32)
	GetX() (_swig_ret float32)
	SetY(arg2 float32)
	GetY() (_swig_ret float32)
	SetZ(arg2 float32)
	GetZ() (_swig_ret float32)
}


