/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: /home/ptriller/projects/github/go-sfml/work/system/System.i

package system

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef void* swig_type_1;
typedef void* swig_type_2;
typedef void* swig_type_3;
typedef void* swig_type_4;
typedef void* swig_type_5;
typedef void* swig_type_6;
typedef void* swig_type_7;
typedef void* swig_type_8;
typedef void* swig_type_9;
typedef long long swig_type_10;
typedef long long swig_type_11;
typedef long long swig_type_12;
typedef long long swig_type_13;
extern void _wrap_Swig_free_system_6b0f4a865dc260a2(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_system_6b0f4a865dc260a2(swig_intgo arg1);
extern uintptr_t _wrap_sfClock_create_system_6b0f4a865dc260a2(void);
extern uintptr_t _wrap_sfClock_copy_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfClock_destroy_system_6b0f4a865dc260a2(uintptr_t arg1);
extern uintptr_t _wrap_sfClock_getElapsedTime_system_6b0f4a865dc260a2(uintptr_t arg1);
extern uintptr_t _wrap_sfClock_restart_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfInputStream_read_set_system_6b0f4a865dc260a2(uintptr_t arg1, swig_type_1 arg2);
extern swig_type_2 _wrap_sfInputStream_read_get_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfInputStream_seek_set_system_6b0f4a865dc260a2(uintptr_t arg1, swig_type_3 arg2);
extern swig_type_4 _wrap_sfInputStream_seek_get_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfInputStream_tell_set_system_6b0f4a865dc260a2(uintptr_t arg1, swig_type_5 arg2);
extern swig_type_6 _wrap_sfInputStream_tell_get_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfInputStream_getSize_set_system_6b0f4a865dc260a2(uintptr_t arg1, swig_type_7 arg2);
extern swig_type_8 _wrap_sfInputStream_getSize_get_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfInputStream_userData_set_system_6b0f4a865dc260a2(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_sfInputStream_userData_get_system_6b0f4a865dc260a2(uintptr_t arg1);
extern uintptr_t _wrap_new_sfInputStream_system_6b0f4a865dc260a2(void);
extern void _wrap_delete_sfInputStream_system_6b0f4a865dc260a2(uintptr_t arg1);
extern uintptr_t _wrap_sfMutex_create_system_6b0f4a865dc260a2(void);
extern void _wrap_sfMutex_destroy_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfMutex_lock_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfMutex_unlock_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfSleep_system_6b0f4a865dc260a2(uintptr_t arg1);
extern uintptr_t _wrap_sfThread_create_system_6b0f4a865dc260a2(swig_type_9 arg1, uintptr_t arg2);
extern void _wrap_sfThread_destroy_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfThread_launch_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfThread_wait_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfThread_terminate_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfTime_microseconds_set_system_6b0f4a865dc260a2(uintptr_t arg1, swig_type_10 arg2);
extern swig_type_11 _wrap_sfTime_microseconds_get_system_6b0f4a865dc260a2(uintptr_t arg1);
extern uintptr_t _wrap_new_sfTime_system_6b0f4a865dc260a2(void);
extern void _wrap_delete_sfTime_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfTime_Zero_set_system_6b0f4a865dc260a2(uintptr_t arg1);
extern uintptr_t _wrap_sfTime_Zero_get_system_6b0f4a865dc260a2(void);
extern float _wrap_sfTime_asSeconds_system_6b0f4a865dc260a2(uintptr_t arg1);
extern swig_intgo _wrap_sfTime_asMilliseconds_system_6b0f4a865dc260a2(uintptr_t arg1);
extern swig_type_12 _wrap_sfTime_asMicroseconds_system_6b0f4a865dc260a2(uintptr_t arg1);
extern uintptr_t _wrap_sfSeconds_system_6b0f4a865dc260a2(float arg1);
extern uintptr_t _wrap_sfMilliseconds_system_6b0f4a865dc260a2(swig_intgo arg1);
extern uintptr_t _wrap_sfMicroseconds_system_6b0f4a865dc260a2(swig_type_13 arg1);
extern void _wrap_sfVector2i_x_set_system_6b0f4a865dc260a2(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_sfVector2i_x_get_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfVector2i_y_set_system_6b0f4a865dc260a2(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_sfVector2i_y_get_system_6b0f4a865dc260a2(uintptr_t arg1);
extern uintptr_t _wrap_new_sfVector2i_system_6b0f4a865dc260a2(void);
extern void _wrap_delete_sfVector2i_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfVector2u_x_set_system_6b0f4a865dc260a2(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_sfVector2u_x_get_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfVector2u_y_set_system_6b0f4a865dc260a2(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_sfVector2u_y_get_system_6b0f4a865dc260a2(uintptr_t arg1);
extern uintptr_t _wrap_new_sfVector2u_system_6b0f4a865dc260a2(void);
extern void _wrap_delete_sfVector2u_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfVector2f_x_set_system_6b0f4a865dc260a2(uintptr_t arg1, float arg2);
extern float _wrap_sfVector2f_x_get_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfVector2f_y_set_system_6b0f4a865dc260a2(uintptr_t arg1, float arg2);
extern float _wrap_sfVector2f_y_get_system_6b0f4a865dc260a2(uintptr_t arg1);
extern uintptr_t _wrap_new_sfVector2f_system_6b0f4a865dc260a2(void);
extern void _wrap_delete_sfVector2f_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfVector3f_x_set_system_6b0f4a865dc260a2(uintptr_t arg1, float arg2);
extern float _wrap_sfVector3f_x_get_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfVector3f_y_set_system_6b0f4a865dc260a2(uintptr_t arg1, float arg2);
extern float _wrap_sfVector3f_y_get_system_6b0f4a865dc260a2(uintptr_t arg1);
extern void _wrap_sfVector3f_z_set_system_6b0f4a865dc260a2(uintptr_t arg1, float arg2);
extern float _wrap_sfVector3f_z_get_system_6b0f4a865dc260a2(uintptr_t arg1);
extern uintptr_t _wrap_new_sfVector3f_system_6b0f4a865dc260a2(void);
extern void _wrap_delete_sfVector3f_system_6b0f4a865dc260a2(uintptr_t arg1);
#undef intgo
*/
// #cgo LDFLAGS: -lcsfml-system
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_system_6b0f4a865dc260a2(C.swig_intgo(_swig_i_0)))
	return swig_r
}

const CSFML_VERSION_MAJOR int = 2
const CSFML_VERSION_MINOR int = 5
const CSFML_VERSION_PATCH int = 0
const SfFalse int = 0
const SfTrue int = 1
func SfClock_create() (_swig_ret Struct_SS_sfClock) {
	var swig_r Struct_SS_sfClock
	swig_r = (Struct_SS_sfClock)(SwigcptrStruct_SS_sfClock(C._wrap_sfClock_create_system_6b0f4a865dc260a2()))
	return swig_r
}

func SfClock_copy(arg1 Struct_SS_sfClock) (_swig_ret Struct_SS_sfClock) {
	var swig_r Struct_SS_sfClock
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_sfClock)(SwigcptrStruct_SS_sfClock(C._wrap_sfClock_copy_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfClock_destroy(arg1 Struct_SS_sfClock) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfClock_destroy_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

func SfClock_getElapsedTime(arg1 Struct_SS_sfClock) (_swig_ret SfTime) {
	var swig_r SfTime
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (SfTime)(SwigcptrSfTime(C._wrap_sfClock_getElapsedTime_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func SfClock_restart(arg1 Struct_SS_sfClock) (_swig_ret SfTime) {
	var swig_r SfTime
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (SfTime)(SwigcptrSfTime(C._wrap_sfClock_restart_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))))
	return swig_r
}

type SwigcptrSfInputStream uintptr

func (p SwigcptrSfInputStream) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSfInputStream) SwigIsSfInputStream() {
}

func (arg1 SwigcptrSfInputStream) SetRead(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfInputStream_read_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0), C.swig_type_1(_swig_i_1))
}

func (arg1 SwigcptrSfInputStream) GetRead() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap_sfInputStream_read_get_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSfInputStream) SetSeek(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfInputStream_seek_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0), C.swig_type_3(_swig_i_1))
}

func (arg1 SwigcptrSfInputStream) GetSeek() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap_sfInputStream_seek_get_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSfInputStream) SetTell(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfInputStream_tell_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0), C.swig_type_5(_swig_i_1))
}

func (arg1 SwigcptrSfInputStream) GetTell() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap_sfInputStream_tell_get_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSfInputStream) SetGetSize(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfInputStream_getSize_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0), C.swig_type_7(_swig_i_1))
}

func (arg1 SwigcptrSfInputStream) GetGetSize() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap_sfInputStream_getSize_get_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSfInputStream) SetUserData(arg2 uintptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfInputStream_userData_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrSfInputStream) GetUserData() (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_sfInputStream_userData_get_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewSfInputStream() (_swig_ret SfInputStream) {
	var swig_r SfInputStream
	swig_r = (SfInputStream)(SwigcptrSfInputStream(C._wrap_new_sfInputStream_system_6b0f4a865dc260a2()))
	return swig_r
}

func DeleteSfInputStream(arg1 SfInputStream) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_sfInputStream_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

type SfInputStream interface {
	Swigcptr() uintptr
	SwigIsSfInputStream()
	SetRead(arg2 _swig_fnptr)
	GetRead() (_swig_ret _swig_fnptr)
	SetSeek(arg2 _swig_fnptr)
	GetSeek() (_swig_ret _swig_fnptr)
	SetTell(arg2 _swig_fnptr)
	GetTell() (_swig_ret _swig_fnptr)
	SetGetSize(arg2 _swig_fnptr)
	GetGetSize() (_swig_ret _swig_fnptr)
	SetUserData(arg2 uintptr)
	GetUserData() (_swig_ret uintptr)
}

func SfMutex_create() (_swig_ret Struct_SS_sfMutex) {
	var swig_r Struct_SS_sfMutex
	swig_r = (Struct_SS_sfMutex)(SwigcptrStruct_SS_sfMutex(C._wrap_sfMutex_create_system_6b0f4a865dc260a2()))
	return swig_r
}

func SfMutex_destroy(arg1 Struct_SS_sfMutex) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfMutex_destroy_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

func SfMutex_lock(arg1 Struct_SS_sfMutex) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfMutex_lock_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

func SfMutex_unlock(arg1 Struct_SS_sfMutex) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfMutex_unlock_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

func SfSleep(arg1 SfTime) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfSleep_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

func SfThread_create(arg1 _swig_fnptr, arg2 uintptr) (_swig_ret Struct_SS_sfThread) {
	var swig_r Struct_SS_sfThread
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Struct_SS_sfThread)(SwigcptrStruct_SS_sfThread(C._wrap_sfThread_create_system_6b0f4a865dc260a2(C.swig_type_9(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func SfThread_destroy(arg1 Struct_SS_sfThread) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfThread_destroy_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

func SfThread_launch(arg1 Struct_SS_sfThread) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfThread_launch_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

func SfThread_wait(arg1 Struct_SS_sfThread) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfThread_wait_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

func SfThread_terminate(arg1 Struct_SS_sfThread) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfThread_terminate_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

type SwigcptrSfTime uintptr

func (p SwigcptrSfTime) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSfTime) SwigIsSfTime() {
}

func (arg1 SwigcptrSfTime) SetMicroseconds(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfTime_microseconds_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0), C.swig_type_10(_swig_i_1))
}

func (arg1 SwigcptrSfTime) GetMicroseconds() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_sfTime_microseconds_get_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewSfTime() (_swig_ret SfTime) {
	var swig_r SfTime
	swig_r = (SfTime)(SwigcptrSfTime(C._wrap_new_sfTime_system_6b0f4a865dc260a2()))
	return swig_r
}

func DeleteSfTime(arg1 SfTime) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_sfTime_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

type SfTime interface {
	Swigcptr() uintptr
	SwigIsSfTime()
	SetMicroseconds(arg2 int64)
	GetMicroseconds() (_swig_ret int64)
}

func SetSfTime_Zero(arg1 SfTime) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_sfTime_Zero_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

func GetSfTime_Zero() (_swig_ret SfTime) {
	var swig_r SfTime
	swig_r = (SfTime)(SwigcptrSfTime(C._wrap_sfTime_Zero_get_system_6b0f4a865dc260a2()))
	return swig_r
}

func SfTime_asSeconds(arg1 SfTime) (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (float32)(C._wrap_sfTime_asSeconds_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfTime_asMilliseconds(arg1 SfTime) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_sfTime_asMilliseconds_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfTime_asMicroseconds(arg1 SfTime) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int64)(C._wrap_sfTime_asMicroseconds_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SfSeconds(arg1 float32) (_swig_ret SfTime) {
	var swig_r SfTime
	_swig_i_0 := arg1
	swig_r = (SfTime)(SwigcptrSfTime(C._wrap_sfSeconds_system_6b0f4a865dc260a2(C.float(_swig_i_0))))
	return swig_r
}

func SfMilliseconds(arg1 int) (_swig_ret SfTime) {
	var swig_r SfTime
	_swig_i_0 := arg1
	swig_r = (SfTime)(SwigcptrSfTime(C._wrap_sfMilliseconds_system_6b0f4a865dc260a2(C.swig_intgo(_swig_i_0))))
	return swig_r
}

func SfMicroseconds(arg1 int64) (_swig_ret SfTime) {
	var swig_r SfTime
	_swig_i_0 := arg1
	swig_r = (SfTime)(SwigcptrSfTime(C._wrap_sfMicroseconds_system_6b0f4a865dc260a2(C.swig_type_13(_swig_i_0))))
	return swig_r
}

type SwigcptrSfVector2i uintptr

func (p SwigcptrSfVector2i) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSfVector2i) SwigIsSfVector2i() {
}

func (arg1 SwigcptrSfVector2i) SetX(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector2i_x_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrSfVector2i) GetX() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_sfVector2i_x_get_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSfVector2i) SetY(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector2i_y_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrSfVector2i) GetY() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_sfVector2i_y_get_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewSfVector2i() (_swig_ret SfVector2i) {
	var swig_r SfVector2i
	swig_r = (SfVector2i)(SwigcptrSfVector2i(C._wrap_new_sfVector2i_system_6b0f4a865dc260a2()))
	return swig_r
}

func DeleteSfVector2i(arg1 SfVector2i) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_sfVector2i_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

type SfVector2i interface {
	Swigcptr() uintptr
	SwigIsSfVector2i()
	SetX(arg2 int)
	GetX() (_swig_ret int)
	SetY(arg2 int)
	GetY() (_swig_ret int)
}

type SwigcptrSfVector2u uintptr

func (p SwigcptrSfVector2u) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSfVector2u) SwigIsSfVector2u() {
}

func (arg1 SwigcptrSfVector2u) SetX(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector2u_x_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrSfVector2u) GetX() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_sfVector2u_x_get_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSfVector2u) SetY(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector2u_y_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrSfVector2u) GetY() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_sfVector2u_y_get_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewSfVector2u() (_swig_ret SfVector2u) {
	var swig_r SfVector2u
	swig_r = (SfVector2u)(SwigcptrSfVector2u(C._wrap_new_sfVector2u_system_6b0f4a865dc260a2()))
	return swig_r
}

func DeleteSfVector2u(arg1 SfVector2u) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_sfVector2u_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

type SfVector2u interface {
	Swigcptr() uintptr
	SwigIsSfVector2u()
	SetX(arg2 uint)
	GetX() (_swig_ret uint)
	SetY(arg2 uint)
	GetY() (_swig_ret uint)
}

type SwigcptrSfVector2f uintptr

func (p SwigcptrSfVector2f) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSfVector2f) SwigIsSfVector2f() {
}

func (arg1 SwigcptrSfVector2f) SetX(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector2f_x_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrSfVector2f) GetX() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_sfVector2f_x_get_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSfVector2f) SetY(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector2f_y_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrSfVector2f) GetY() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_sfVector2f_y_get_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewSfVector2f() (_swig_ret SfVector2f) {
	var swig_r SfVector2f
	swig_r = (SfVector2f)(SwigcptrSfVector2f(C._wrap_new_sfVector2f_system_6b0f4a865dc260a2()))
	return swig_r
}

func DeleteSfVector2f(arg1 SfVector2f) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_sfVector2f_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

type SfVector2f interface {
	Swigcptr() uintptr
	SwigIsSfVector2f()
	SetX(arg2 float32)
	GetX() (_swig_ret float32)
	SetY(arg2 float32)
	GetY() (_swig_ret float32)
}

type SwigcptrSfVector3f uintptr

func (p SwigcptrSfVector3f) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSfVector3f) SwigIsSfVector3f() {
}

func (arg1 SwigcptrSfVector3f) SetX(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector3f_x_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrSfVector3f) GetX() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_sfVector3f_x_get_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSfVector3f) SetY(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector3f_y_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrSfVector3f) GetY() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_sfVector3f_y_get_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSfVector3f) SetZ(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_sfVector3f_z_set_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrSfVector3f) GetZ() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_sfVector3f_z_get_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewSfVector3f() (_swig_ret SfVector3f) {
	var swig_r SfVector3f
	swig_r = (SfVector3f)(SwigcptrSfVector3f(C._wrap_new_sfVector3f_system_6b0f4a865dc260a2()))
	return swig_r
}

func DeleteSfVector3f(arg1 SfVector3f) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_sfVector3f_system_6b0f4a865dc260a2(C.uintptr_t(_swig_i_0))
}

type SfVector3f interface {
	Swigcptr() uintptr
	SwigIsSfVector3f()
	SetX(arg2 float32)
	GetX() (_swig_ret float32)
	SetY(arg2 float32)
	GetY() (_swig_ret float32)
	SetZ(arg2 float32)
	GetZ() (_swig_ret float32)
}


type SwigcptrStruct_SS_sfClock uintptr
type Struct_SS_sfClock interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_sfClock) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_sfThread uintptr
type Struct_SS_sfThread interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_sfThread) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_sfMutex uintptr
type Struct_SS_sfMutex interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_sfMutex) Swigcptr() uintptr {
	return uintptr(p)
}

